// Code generated by abstraction-idl from abstraction-logging/logging.thrift. DO NOT EDIT.

#pragma once

#include <cstddef>
#include <cstdint>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

namespace abstraction::logging {

using Raw = std::string;

inline void esc(std::string& out, const std::string& s);

inline void esc_byte(std::string& out, unsigned char c) {
    static const char* kHex = "0123456789abcdef";
    switch (c) {
        case '"': out += "\\\""; return;
        case '\\': out += "\\\\"; return;
        case 0x08: out += "\\b"; return;
        case 0x0c: out += "\\f"; return;
        case '\n': out += "\\n"; return;
        case '\r': out += "\\r"; return;
        case '\t': out += "\\t"; return;
        default: break;
    }
    if (c < 0x20) {
        out += "\\u00";
        out += kHex[c >> 4];
        out += kHex[c & 0x0F];
    } else {
        out += static_cast<char>(c);
    }
}

inline void num(std::string& out, std::int64_t n) { out += std::to_string(n); }

inline void pad(std::string& out, int depth) {
    out.append(static_cast<std::size_t>(depth) * 2, ' ');
}

inline void strs(std::string& out, const std::vector<std::string>& v, int depth) {
    if (v.empty()) { out += "[]"; return; }
    out += "[\n";
    for (std::size_t i = 0; i < v.size(); ++i) {
        pad(out, depth + 1);
        esc(out, v[i]);
        if (i + 1 < v.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += ']';
}

inline bool ws(unsigned char c) { return c == ' ' || c == '\t' || c == '\n' || c == '\r'; }

inline void raw(std::string& out, const std::string& s, int depth) {
    const std::size_t n = s.size();
    for (std::size_t i = 0; i < n;) {
        const unsigned char c = static_cast<unsigned char>(s[i]);
        if (ws(c)) {
            ++i;
        } else if (c == '"') {
            std::size_t j = i + 1;
            while (j < n) {
                if (s[j] == '\\') { j += 2; continue; }
                if (s[j] == '"') { ++j; break; }
                ++j;
            }
            out.append(s, i, j - i);
            i = j;
        } else if (c == '{' || c == '[') {
            out += static_cast<char>(c);
            ++i;
            std::size_t j = i;
            while (j < n && ws(static_cast<unsigned char>(s[j]))) ++j;
            if (j < n && (s[j] == '}' || s[j] == ']')) {
                out += s[j];
                i = j + 1;
            } else {
                ++depth;
                out += '\n';
                pad(out, depth);
            }
        } else if (c == '}' || c == ']') {
            --depth;
            out += '\n';
            pad(out, depth);
            out += static_cast<char>(c);
            ++i;
        } else if (c == ',') {
            out += ",\n";
            pad(out, depth);
            ++i;
        } else if (c == ':') {
            out += ": ";
            ++i;
        } else {
            out += static_cast<char>(c);
            ++i;
        }
    }
}

// std::char_traits<char>::compare is specified to order by unsigned char, so a
// std::map<std::string, ...> already walks its keys in UTF-8 byte order — which
// is what the definition declares. Nothing sorts here because nothing needs to.
inline void rawmap(std::string& out, const std::map<std::string, Raw>& m, int depth) {
    if (m.empty()) { out += "{}"; return; }
    out += "{\n";
    std::size_t i = 0;
    for (const auto& kv : m) {
        pad(out, depth + 1);
        esc(out, kv.first);
        out += ": ";
        raw(out, kv.second, depth + 1);
        if (++i < m.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += '}';
}

inline void esc(std::string& out, const std::string& s) {
    out += '"';
    for (unsigned char c : s) esc_byte(out, c);
    out += '"';
}

class Refusal : public std::runtime_error {
public:
    Refusal(const char* word, std::size_t offset)
        : std::runtime_error(std::string("refused: ") + word + " at byte " + std::to_string(offset)),
          word(word),
          offset(offset) {}
    const char* word;
    std::size_t offset;
};

inline bool wide_timestamp(std::string_view);
inline std::string normalized_timestamp(std::string_view);
inline std::string write_timestamp(std::string_view);

inline void strmap(std::string& out, const std::map<std::string, std::string>& m, int depth) {
    if (m.empty()) { out += "{}"; return; }
    out += "{\n";
    std::size_t i = 0;
    for (const auto& kv : m) {
        pad(out, depth + 1);
        esc(out, kv.first);
        out += ": ";
        esc(out, kv.second);
        if (++i < m.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += '}';
}

template <typename T>
inline void enc_list(std::string& out, const std::vector<T>& v, int depth,
                     void (*enc)(std::string&, const T&, int)) {
    if (v.empty()) { out += "[]"; return; }
    out += "[\n";
    for (std::size_t i = 0; i < v.size(); ++i) {
        pad(out, depth + 1);
        enc(out, v[i], depth + 1);
        if (i + 1 < v.size()) out += ',';
        out += '\n';
    }
    pad(out, depth);
    out += ']';
}

struct Attestation {
    std::string by;
    bool verified = false;
    std::int64_t hop = 0;
    std::string program;
    std::string host;
    std::string user;
    std::string exe;
    std::int64_t uid = 0;
    std::int64_t gid = 0;
    std::int64_t pid = 0;
    std::string key;
    std::string mac;
};

struct Record {
    std::int64_t schema = 0;
    std::string time;
    std::int64_t level = 0;
    std::string msg;
    std::vector<Attestation> identity;
    std::string job;
    std::map<std::string, std::string> attrs;
};

struct OASinkWriteArguments {
    Record record;
};

struct OAServiceFrame {
    std::int32_t version = 0;
    std::string service;
    std::string method;
    Raw arguments;
};

inline void enc_attestation(std::string& out, const Attestation& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "by");
    out += ": ";
    esc(out, v.by);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "verified");
    out += ": ";
    out += v.verified ? "true" : "false";
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "hop");
    out += ": ";
    num(out, v.hop);
    if (!v.program.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "program");
        out += ": ";
        esc(out, v.program);
    }
    if (!v.host.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "host");
        out += ": ";
        esc(out, v.host);
    }
    if (!v.user.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "user");
        out += ": ";
        esc(out, v.user);
    }
    if (!v.exe.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "exe");
        out += ": ";
        esc(out, v.exe);
    }
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "uid");
    out += ": ";
    num(out, v.uid);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "gid");
    out += ": ";
    num(out, v.gid);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "pid");
    out += ": ";
    num(out, v.pid);
    if (!v.key.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "key");
        out += ": ";
        esc(out, v.key);
    }
    if (!v.mac.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "mac");
        out += ": ";
        esc(out, v.mac);
    }
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_record(std::string& out, const Record& v, int depth) {
    if (v.schema != 1LL) throw Refusal("bad_schema",0);
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "schema");
    out += ": ";
    num(out, v.schema);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "time");
    out += ": ";
    esc(out, write_timestamp(v.time));
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "level");
    out += ": ";
    num(out, v.level);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "msg");
    out += ": ";
    esc(out, v.msg);
    if (!v.identity.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "identity");
        out += ": ";
        enc_list<Attestation>(out, v.identity, depth + 1, enc_attestation);
    }
    if (!v.job.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "job");
        out += ": ";
        esc(out, v.job);
    }
    if (!v.attrs.empty()) {
        out += ',';
        out += '\n';
        pad(out, depth + 1);
        esc(out, "attrs");
        out += ": ";
        strmap(out, v.attrs, depth + 1);
    }
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oasinkwritearguments(std::string& out, const OASinkWriteArguments& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "record");
    out += ": ";
    enc_record(out, v.record, depth + 1);
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline void enc_oaserviceframe(std::string& out, const OAServiceFrame& v, int depth) {
    out += '{';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "version");
    out += ": ";
    num(out, v.version);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "service");
    out += ": ";
    esc(out, v.service);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "method");
    out += ": ";
    esc(out, v.method);
    out += ',';
    out += '\n';
    pad(out, depth + 1);
    esc(out, "arguments");
    out += ": ";
    out += v.arguments;
    out += '\n';
    pad(out, depth);
    out += '}';
}

inline std::string encode(const Record& v) {
    std::string out;
    enc_record(out, v, 0);
    out += '\n';
    return out;
}

inline constexpr int kDepthLimit = 64;
inline constexpr std::size_t kI64Digits = 19;



inline void append_rune(std::string& out, std::uint32_t cp) {
    if (cp < 0x80) {
        out += static_cast<char>(cp);
    } else if (cp < 0x800) {
        out += static_cast<char>(0xC0 | (cp >> 6));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else if (cp < 0x10000) {
        out += static_cast<char>(0xE0 | (cp >> 12));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    } else {
        out += static_cast<char>(0xF0 | (cp >> 18));
        out += static_cast<char>(0x80 | ((cp >> 12) & 0x3F));
        out += static_cast<char>(0x80 | ((cp >> 6) & 0x3F));
        out += static_cast<char>(0x80 | (cp & 0x3F));
    }
}

inline bool valid_utf8(const std::string& b) {
    for (std::size_t i = 0; i < b.size();) {
        const unsigned char c = static_cast<unsigned char>(b[i]);
        if (c < 0x80) { ++i; continue; }
        std::size_t n = 0;
        std::uint32_t cp = 0;
        if ((c >> 5) == 0x6) { n = 2; cp = c & 0x1Fu; }
        else if ((c >> 4) == 0xE) { n = 3; cp = c & 0x0Fu; }
        else if ((c >> 3) == 0x1E) { n = 4; cp = c & 0x07u; }
        else return false;
        if (i + n > b.size()) return false;
        for (std::size_t k = 1; k < n; ++k) {
            const unsigned char t = static_cast<unsigned char>(b[i + k]);
            if ((t >> 6) != 0x2) return false;
            cp = cp << 6 | (t & 0x3Fu);
        }
        static const std::uint32_t kLowest[5] = {0, 0, 0x80, 0x800, 0x10000};
        if (cp < kLowest[n] || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF)) return false;
        i += n;
    }
    return true;
}

struct Reader {
    std::string_view buf;
    std::size_t pos = 0;
    int depth = 0;

    [[noreturn]] void refuse(const char* word) const { throw Refusal(word, pos); }

    unsigned char at() const {
        return pos < buf.size() ? static_cast<unsigned char>(buf[pos]) : 0;
    }

    bool digit() const { return at() >= '0' && at() <= '9'; }

    void skip_ws() {
        while (pos < buf.size() && ws(static_cast<unsigned char>(buf[pos]))) ++pos;
    }

    void enter() {
        if (++depth > kDepthLimit) refuse("depth_exceeded");
    }

    std::string str() {
        if (at() != '"') refuse("wrong_type");
        ++pos;
        std::string out;
        for (;;) {
            if (pos >= buf.size()) refuse("malformed");
            const unsigned char c = static_cast<unsigned char>(buf[pos]);
            if (c == '"') {
                ++pos;
                if (!valid_utf8(out)) refuse("bad_string");
                return out;
            }
            if (c < 0x20) refuse("bad_string");
            if (c == '\\') {
                escape(out);
            } else {
                out += static_cast<char>(c);
                ++pos;
            }
        }
    }

    void escape(std::string& out) {
        ++pos;
        if (pos >= buf.size()) refuse("malformed");
        const unsigned char c = static_cast<unsigned char>(buf[pos]);
        ++pos;
        switch (c) {
            case '"': case '\\': case '/': out += static_cast<char>(c); return;
            case 'b': out += static_cast<char>(0x08); return;
            case 'f': out += static_cast<char>(0x0c); return;
            case 'n': out += '\n'; return;
            case 'r': out += '\r'; return;
            case 't': out += '\t'; return;
            case 'u': break;
            default: refuse("bad_string");
        }
        std::uint32_t u = hex4();
        if (u >= 0xDC00 && u <= 0xDFFF) refuse("bad_string");
        if (u >= 0xD800 && u <= 0xDBFF) {
            if (pos + 1 >= buf.size() || buf[pos] != '\\' || buf[pos + 1] != 'u') refuse("bad_string");
            pos += 2;
            const std::uint32_t low = hex4();
            if (low < 0xDC00 || low > 0xDFFF) refuse("bad_string");
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
        }
        append_rune(out, u);
    }

    std::uint32_t hex4() {
        if (pos + 4 > buf.size()) refuse("bad_string");
        std::uint32_t u = 0;
        for (std::size_t i = 0; i < 4; ++i) {
            const unsigned char c = static_cast<unsigned char>(buf[pos + i]);
            if (c >= '0' && c <= '9') u = u << 4 | static_cast<std::uint32_t>(c - '0');
            else if (c >= 'a' && c <= 'f') u = u << 4 | static_cast<std::uint32_t>(c - 'a' + 10);
            else if (c >= 'A' && c <= 'F') u = u << 4 | static_cast<std::uint32_t>(c - 'A' + 10);
            else refuse("bad_string");
        }
        pos += 4;
        return u;
    }

    std::int64_t integer(std::int64_t low, std::int64_t high) {
        const unsigned char c = at();
        if (c != '-' && !digit()) refuse("wrong_type");
        const bool negative = c == '-';
        if (negative) ++pos;
        if (!digit()) refuse("malformed");
        std::uint64_t u = 0;
        if (at() == '0') {
            ++pos;
        } else {
            while (digit()) {
                if (u > 922337203685477580ULL) refuse("number_spelling");
                u = u * 10 + static_cast<std::uint64_t>(at() - '0');
                ++pos;
            }
        }
        const unsigned char after = at();
        if (after == '.' || after == 'e' || after == 'E' || digit()) refuse("number_spelling");
        if (negative && u == 0) refuse("number_spelling");
        std::int64_t n = 0;
        if (negative) {
            if (u > (1ULL << 63)) refuse("number_spelling");
            n = u == (1ULL << 63) ? INT64_MIN : -static_cast<std::int64_t>(u);
        } else {
            if (u > static_cast<std::uint64_t>(INT64_MAX)) refuse("number_spelling");
            n = static_cast<std::int64_t>(u);
        }
        if (n < low || n > high) refuse("number_spelling");
        return n;
    }

    bool boolean() {
        if (at() == 't') { literal("true"); return true; }
        if (at() == 'f') { literal("false"); return false; }
        refuse("wrong_type");
    }

    void literal(std::string_view word) {
        if (buf.substr(pos, word.size()) != word) refuse("malformed");
        pos += word.size();
    }

    std::vector<std::string> str_list() {
        if (at() != '[') refuse("wrong_type");
        enter();
        ++pos;
        std::vector<std::string> out;
        skip_ws();
        if (at() != ']') {
            for (;;) {
                skip_ws();
                out.push_back(str());
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != ']') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    std::map<std::string, Raw> raw_map() {
        if (at() != '{') refuse("wrong_type");
        enter();
        ++pos;
        std::map<std::string, Raw> out;
        skip_ws();
        if (at() != '}') {
            for (;;) {
                skip_ws();
                if (at() != '"') refuse("malformed");
                const std::string k = str();
                skip_ws();
                if (at() != ':') refuse("malformed");
                ++pos;
                skip_ws();
                out[k] = raw_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != '}') refuse("malformed");
        ++pos;
        --depth;
        return out;
    }

    Raw raw_value() {
        const std::size_t start = pos;
        skip_value();
        return std::string(buf.substr(start, pos - start));
    }

    void skip_value() {
        const unsigned char c = at();
        if (c == '"') skip_string();
        else if (c == '{' || c == '[') skip_container();
        else if (c == 't') literal("true");
        else if (c == 'f') literal("false");
        else if (c == 'n') literal("null");
        else if (c == '-' || digit()) skip_number();
        else refuse("malformed");
    }

    // An opaque value is validated and carried, never interpreted. Its syntax is
    // the record's own — the same string reader, so an escape, a control byte or
    // a lone surrogate is judged identically at any depth — and what it is free
    // to spell, it keeps: the bytes between these two offsets are what a writer
    // re-emits. A number is walked, never converted, so a value no host type
    // holds survives the reader that carried it.
    void skip_string() { str(); }

    void some_digits() {
        int n = 0;
        while (digit()) { ++pos; ++n; }
        if (n == 0) refuse("number_spelling");
    }

    void skip_number() {
        if (at() == '-') ++pos;
        const unsigned char c = at();
        if (c == '0') ++pos;
        else if (c >= '1' && c <= '9') { while (digit()) ++pos; }
        else refuse("number_spelling");
        if (at() == '.') { ++pos; some_digits(); }
        if (at() == 'e' || at() == 'E') {
            ++pos;
            if (at() == '+' || at() == '-') ++pos;
            some_digits();
        }
    }

    void skip_container() {
        const unsigned char opener = at();
        const char shut = opener == '{' ? '}' : ']';
        enter();
        ++pos;
        skip_ws();
        if (at() != static_cast<unsigned char>(shut)) {
            for (;;) {
                skip_ws();
                if (opener == '{') {
                    if (at() != '"') refuse("malformed");
                    str();
                    skip_ws();
                    if (at() != ':') refuse("malformed");
                    ++pos;
                    skip_ws();
                }
                skip_value();
                skip_ws();
                if (at() != ',') break;
                ++pos;
            }
        }
        if (at() != static_cast<unsigned char>(shut)) refuse("malformed");
        ++pos;
        --depth;
    }
};

inline std::map<std::string, std::string> str_map(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    std::map<std::string, std::string> out;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string k = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            out[k] = r.str();
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    return out;
}

template <typename T>
inline std::vector<T> decode_list(Reader& r, T (*elem)(Reader&)) {
    if (r.at() != '[') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    std::vector<T> out;
    r.skip_ws();
    if (r.at() != ']') {
        for (;;) {
            r.skip_ws();
            out.push_back(elem(r));
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != ']') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    return out;
}

inline bool digits(std::string_view s, std::size_t i, std::size_t n) {
    if (s.size() < i + n) return false;
    for (std::size_t k = 0; k < n; ++k) {
        if (s[i + k] < '0' || s[i + k] > '9') return false;
    }
    return true;
}

inline bool date_part(std::string_view s) {
    return s.size() >= 19 && digits(s, 0, 4) && s[4] == '-' && digits(s, 5, 2) && s[7] == '-' &&
           digits(s, 8, 2) && digits(s, 11, 2) && s[13] == ':' && digits(s, 14, 2) && s[16] == ':' &&
           digits(s, 17, 2);
}

// [DEF-G1] rfc3339-wide: what a reader accepts. Any fraction of one to nine
// digits or none, either case of the separators, and a numeric offset.
inline bool lexical_timestamp(std::string_view s) {
    if (!date_part(s) || (s[10] != 'T' && s[10] != 't')) return false;
    std::size_t i = 19;
    if (i < s.size() && s[i] == '.') {
        ++i;
        const std::size_t start = i;
        while (i < s.size() && s[i] >= '0' && s[i] <= '9') ++i;
        if (i - start < 1 || i - start > 9) return false;
    }
    if (i >= s.size()) return false;
    if (s[i] == 'Z' || s[i] == 'z') return i + 1 == s.size();
    if (s[i] != '+' && s[i] != '-') return false;
    return s.size() == i + 6 && digits(s, i + 1, 2) && s[i + 3] == ':' && digits(s, i + 4, 2);
}

// [DEF-G2] rfc3339-micros: what a writer emits. Exactly six fractional digits,
// upper-case separators, UTC.
inline bool micros_timestamp(std::string_view s) {
    return s.size() == 27 && normalized_timestamp(s) == s;
}

inline std::string read_timestamp(Reader& r) {
    const std::size_t at = r.pos;
    const std::string s = r.str();
    if (!wide_timestamp(s)) {
        r.pos = at;
        r.refuse("bad_timestamp");
    }
    return s;
}

inline int timestamp_number(std::string_view s, std::size_t at, std::size_t n) {
    int v=0; for(std::size_t k=0;k<n;++k) v=v*10+(s[at+k]-'0'); return v;
}
inline int timestamp_days(int y, int m) {
    if(m==2) return y%4==0 && (y%100!=0 || y%400==0) ? 29 : 28;
    return m==4 || m==6 || m==9 || m==11 ? 30 : 31;
}
inline std::string normalized_timestamp(std::string_view s) {
    if(!lexical_timestamp(s)) return {};
    int y=timestamp_number(s,0,4), m=timestamp_number(s,5,2), d=timestamp_number(s,8,2);
    int h=timestamp_number(s,11,2), minute=timestamp_number(s,14,2), sec=timestamp_number(s,17,2);
    if(m<1 || m>12 || d<1 || d>timestamp_days(y,m) || h>23 || minute>59 || sec>59) return {};
    std::size_t i=19; std::string_view fraction;
    if(s[i]=='.') {const auto start=++i; while(s[i]>='0' && s[i]<='9') ++i; fraction=s.substr(start,i-start);}
    int total=h*60+minute;
    if(s[i]=='+' || s[i]=='-') {
        int oh=timestamp_number(s,i+1,2), om=timestamp_number(s,i+4,2);
        if(oh>23 || om>59) return {};
        total += (s[i]=='+' ? -1 : 1)*(oh*60+om);
    }
    if(total<0) {total+=1440; --d;} else if(total>=1440) {total-=1440; ++d;}
    if(d==0) {--m; if(m==0) {--y; m=12;} d=timestamp_days(y,m);}
    if(d>timestamp_days(y,m)) {d=1; ++m; if(m==13) {++y; m=1;}}
    if(y<0 || y>9999) return {};
    std::string out="0000-00-00T00:00:00.000000Z";
    auto put=[&](int at,int width,int value) {for(int k=width-1;k>=0;--k) {out[at+k]=char('0'+value%10); value/=10;}};
    put(0,4,y); put(5,2,m); put(8,2,d); put(11,2,total/60); put(14,2,total%60); put(17,2,sec);
    for(std::size_t k=0;k<6 && k<fraction.size();++k) out[20+k]=fraction[k];
    return out;
}
inline bool wide_timestamp(std::string_view s) {return !normalized_timestamp(s).empty();}
inline std::string write_timestamp(std::string_view s) {
    auto result=normalized_timestamp(s);
    if(result.empty()) throw Refusal("bad_timestamp",0);
    return result;
}

inline Attestation decode_attestation(Reader& r);
inline Record decode_record(Reader& r);
inline OASinkWriteArguments decode_oasinkwritearguments(Reader& r);
inline OAServiceFrame decode_oaserviceframe(Reader& r);

inline Attestation decode_attestation(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Attestation v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "by") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.by = r.str();
            } else if (key == "verified") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.verified = r.boolean();
            } else if (key == "hop") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.hop = r.integer(INT64_MIN, INT64_MAX);
            } else if (key == "program") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.program = r.str();
            } else if (key == "host") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.host = r.str();
            } else if (key == "user") {
                if (seen & 32u) r.refuse("duplicate_field");
                seen |= 32u;
                v.user = r.str();
            } else if (key == "exe") {
                if (seen & 64u) r.refuse("duplicate_field");
                seen |= 64u;
                v.exe = r.str();
            } else if (key == "uid") {
                if (seen & 128u) r.refuse("duplicate_field");
                seen |= 128u;
                v.uid = r.integer(INT64_MIN, INT64_MAX);
            } else if (key == "gid") {
                if (seen & 256u) r.refuse("duplicate_field");
                seen |= 256u;
                v.gid = r.integer(INT64_MIN, INT64_MAX);
            } else if (key == "pid") {
                if (seen & 512u) r.refuse("duplicate_field");
                seen |= 512u;
                v.pid = r.integer(INT64_MIN, INT64_MAX);
            } else if (key == "key") {
                if (seen & 1024u) r.refuse("duplicate_field");
                seen |= 1024u;
                v.key = r.str();
            } else if (key == "mac") {
                if (seen & 2048u) r.refuse("duplicate_field");
                seen |= 2048u;
                v.mac = r.str();
            } else {
                r.skip_value();
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 903u) != 903u) r.refuse("missing_field");
    return v;
}

inline Record decode_record(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    Record v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "schema") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.schema = r.integer(INT64_MIN, INT64_MAX);
            } else if (key == "time") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.time = read_timestamp(r);
            } else if (key == "level") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.level = r.integer(INT64_MIN, INT64_MAX);
            } else if (key == "msg") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.msg = r.str();
            } else if (key == "identity") {
                if (seen & 16u) r.refuse("duplicate_field");
                seen |= 16u;
                v.identity = decode_list<Attestation>(r, decode_attestation);
            } else if (key == "job") {
                if (seen & 32u) r.refuse("duplicate_field");
                seen |= 32u;
                v.job = r.str();
            } else if (key == "attrs") {
                if (seen & 64u) r.refuse("duplicate_field");
                seen |= 64u;
                v.attrs = str_map(r);
            } else {
                r.skip_value();
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 15u) != 15u) r.refuse("missing_field");
    if (v.schema != 1LL) r.refuse("bad_schema");
    return v;
}

inline OASinkWriteArguments decode_oasinkwritearguments(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OASinkWriteArguments v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "record") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.record = decode_record(r);
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 1u) != 1u) r.refuse("missing_field");
    return v;
}

inline OAServiceFrame decode_oaserviceframe(Reader& r) {
    if (r.at() != '{') r.refuse("wrong_type");
    r.enter();
    ++r.pos;
    OAServiceFrame v;
    std::uint32_t seen = 0;
    r.skip_ws();
    if (r.at() != '}') {
        for (;;) {
            r.skip_ws();
            if (r.at() != '"') r.refuse("malformed");
            const std::string key = r.str();
            r.skip_ws();
            if (r.at() != ':') r.refuse("malformed");
            ++r.pos;
            r.skip_ws();
            if (key == "version") {
                if (seen & 1u) r.refuse("duplicate_field");
                seen |= 1u;
                v.version = static_cast<std::int32_t>(r.integer(INT32_MIN, INT32_MAX));
            } else if (key == "service") {
                if (seen & 2u) r.refuse("duplicate_field");
                seen |= 2u;
                v.service = r.str();
            } else if (key == "method") {
                if (seen & 4u) r.refuse("duplicate_field");
                seen |= 4u;
                v.method = r.str();
            } else if (key == "arguments") {
                if (seen & 8u) r.refuse("duplicate_field");
                seen |= 8u;
                v.arguments = r.raw_value();
            } else {
                r.refuse("unknown_field");
            }
            r.skip_ws();
            if (r.at() != ',') break;
            ++r.pos;
        }
    }
    if (r.at() != '}') r.refuse("malformed");
    ++r.pos;
    --r.depth;
    if ((seen & 15u) != 15u) r.refuse("missing_field");
    return v;
}

inline Record decode(std::string_view data) {
    Reader r{data};
    r.skip_ws();
    Record v = decode_record(r);
    r.skip_ws();
    if (r.pos < r.buf.size()) r.refuse("trailing_bytes");
    return v;
}

// kRefusals is in the order two of them are chosen between.
inline const std::vector<std::string> kRefusals = {"malformed", "bad_string", "number_spelling", "wrong_type", "bad_timestamp", "depth_exceeded", "duplicate_field", "unknown_field", "missing_field", "bad_schema", "trailing_bytes"};

inline int refusal_rank(std::string_view word) {
    for (std::size_t i = 0; i < kRefusals.size(); ++i)
        if (kRefusals[i] == word) return static_cast<int>(i);
    return -1;
}

struct FrameWriter{virtual ~FrameWriter()=default;virtual void WriteFrame(std::string_view)=0;};
struct DispatchError:std::runtime_error{using std::runtime_error::runtime_error;};
inline OAServiceFrame service_payload(std::string_view frame){Reader r{frame};r.skip_ws();auto v=decode_oaserviceframe(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");if(v.version!=1)throw DispatchError("unknown_version");return v;}
struct Sink{virtual ~Sink()=default;
virtual void Write(const Record& arg0)=0;
};
template<class Transport>struct SinkClient:Sink{Transport& transport_;explicit SinkClient(Transport&t):transport_(t){}
void Write(const Record& arg0)override{OASinkWriteArguments args;
args.record=arg0;
OAServiceFrame v;v.version=1;v.service="abstraction.logging/sink@1";v.method="Write";enc_oasinkwritearguments(v.arguments,args,1);std::string frame;enc_oaserviceframe(frame,v,0);service_payload(frame);
transport_.WriteFrame(frame);}
};
struct SinkDispatcher:FrameWriter{Sink&handler;explicit SinkDispatcher(Sink&h):handler(h){}
void WriteFrame(std::string_view frame)override{auto v=service_payload(frame);if(v.service!="abstraction.logging/sink@1")throw DispatchError("unknown_service");
if(v.method=="Write"){
Reader r{v.arguments};r.depth=1;r.skip_ws();auto args=decode_oasinkwritearguments(r);r.skip_ws();if(r.pos!=r.buf.size())r.refuse("trailing_bytes");handler.Write(args.record);return;}
throw DispatchError("unknown_method");}
};

}  // namespace abstraction::logging
