# Code generated by abstraction-idl from abstraction-logging/logging.thrift. DO NOT EDIT.

_HEX = b"0123456789abcdef"
_WS = (0x20, 0x09, 0x0A, 0x0D)
_SHORT = {0x22: b'\\"', 0x5C: b"\\\\", 0x08: b"\\b", 0x0C: b"\\f",
          0x0A: b"\\n", 0x0D: b"\\r", 0x09: b"\\t"}


def esc_byte(out, c):
    short = _SHORT.get(c)
    if short is not None:
        out += short
    elif c < 0x20:
        out += b"\\u00" + bytes([_HEX[c >> 4], _HEX[c & 0xF]])
    else:
        out.append(c)


def num(out, n):
    out += str(int(n)).encode("ascii")


def pad(out, depth):
    out += b" " * (depth * 2)


def strs(out, v, depth):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, s in enumerate(v):
        pad(out, depth + 1)
        esc(out, s)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"]"


def raw(out, s, depth):
    b = s.encode("utf-8") if isinstance(s, str) else s
    i, n = 0, len(b)
    while i < n:
        c = b[i]
        if c in _WS:
            i += 1
        elif c == 0x22:
            j = i + 1
            while j < n:
                if b[j] == 0x5C:
                    j += 2
                    continue
                if b[j] == 0x22:
                    j += 1
                    break
                j += 1
            out += b[i:j]
            i = j
        elif c in (0x7B, 0x5B):
            out.append(c)
            i += 1
            j = i
            while j < n and b[j] in _WS:
                j += 1
            if j < n and b[j] in (0x7D, 0x5D):
                out.append(b[j])
                i = j + 1
            else:
                depth += 1
                out += b"\n"
                pad(out, depth)
        elif c in (0x7D, 0x5D):
            depth -= 1
            out += b"\n"
            pad(out, depth)
            out.append(c)
            i += 1
        elif c == 0x2C:
            out += b",\n"
            pad(out, depth)
            i += 1
        elif c == 0x3A:
            out += b": "
            i += 1
        else:
            out.append(c)
            i += 1


def rawmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        pad(out, depth + 1)
        esc(out, k)
        out += b": "
        raw(out, m[k], depth + 1)
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"}"

def esc(out, s):
    out += b'"'
    for c in s.encode("utf-8"):
        esc_byte(out, c)
    out += b'"'


def strmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        pad(out, depth + 1)
        esc(out, k)
        out += b": "
        esc(out, m[k])
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_list(out, v, depth, enc):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, x in enumerate(v):
        pad(out, depth + 1)
        enc(out, x, depth + 1)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"]"


PAGEOUTCOME_NAMES = ["page", "gap", "unavailable", "invalid_request", "record_too_large", "corrupt", "unsupported"]
PAGEOUTCOME_UNKNOWN = "refuse"


# One hop of the provenance chain. program is the name a party gives itself and
# appears on the writer's self claim. exe is the executable path the attesting
# mechanism resolved for the party it established; a receiving service's stamp
# sets exe and leaves program empty. user is the account name or Windows SID;
# uid and gid are -1 where unestablished.
class Attestation:
    def __init__(self, **kw):
        self.by = kw.get("by", "")
        self.verified = kw.get("verified", False)
        self.hop = kw.get("hop", 0)
        self.program = kw.get("program", "")
        self.host = kw.get("host", "")
        self.user = kw.get("user", "")
        self.exe = kw.get("exe", "")
        self.uid = kw.get("uid", 0)
        self.gid = kw.get("gid", 0)
        self.pid = kw.get("pid", 0)
        self.key = kw.get("key", "")
        self.mac = kw.get("mac", "")


class Record:
    def __init__(self, **kw):
        self.schema = kw.get("schema", 0)
        self.time = kw.get("time", "")
        self.level = kw.get("level", 0)
        self.msg = kw.get("msg", "")
        self.identity = kw.get("identity", [])
        self.job = kw.get("job", "")
        self.attrs = kw.get("attrs", {})


# A bounded page in provider append order. next is an opaque continuation bound
# to this history instance. at_end means the observed end during this call;
# later records may appear. Refusals contain no records and never advance a
# supplied cursor. gap requires an explicit restart with empty cursor; it never
# silently restarts a stream.
class Page:
    def __init__(self, **kw):
        self.outcome = kw.get("outcome", "")
        self.records = kw.get("records", [])
        self.next = kw.get("next", "")
        self.at_end = kw.get("at_end", False)


class OASinkWriteArguments:
    def __init__(self, **kw):
        self.record = kw.get("record", Record())


class OAHistoryReaderReadArguments:
    def __init__(self, **kw):
        self.cursor = kw.get("cursor", "")
        self.max_records = kw.get("max_records", 0)
        self.max_bytes = kw.get("max_bytes", 0)


class OAHistoryObserverObserveArguments:
    def __init__(self, **kw):
        self.cursor = kw.get("cursor", "")
        self.max_records = kw.get("max_records", 0)
        self.max_bytes = kw.get("max_bytes", 0)
        self.wait_ms = kw.get("wait_ms", 0)


class OAServiceFrame:
    def __init__(self, **kw):
        self.version = kw.get("version", 0)
        self.service = kw.get("service", "")
        self.method = kw.get("method", "")
        self.arguments = kw.get("arguments", "")


class OAServiceReply:
    def __init__(self, **kw):
        self.version = kw.get("version", 0)
        self.service = kw.get("service", "")
        self.method = kw.get("method", "")
        self.ok = kw.get("ok", False)
        self.payload = kw.get("payload", "")


class OAServiceError:
    def __init__(self, **kw):
        self.code = kw.get("code", "")
        self.message = kw.get("message", "")


class OAHistoryReaderReadResult:
    def __init__(self, **kw):
        self.value = kw.get("value", Page())


class OAHistoryObserverObserveResult:
    def __init__(self, **kw):
        self.value = kw.get("value", Page())


def enc_attestation(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "by")
    out += b": "
    esc(out, v.by)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "verified")
    out += b": "
    out += b"true" if v.verified else b"false"
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "hop")
    out += b": "
    num(out, v.hop)
    if v.program:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "program")
        out += b": "
        esc(out, v.program)
    if v.host:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "host")
        out += b": "
        esc(out, v.host)
    if v.user:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "user")
        out += b": "
        esc(out, v.user)
    if v.exe:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "exe")
        out += b": "
        esc(out, v.exe)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "uid")
    out += b": "
    num(out, v.uid)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "gid")
    out += b": "
    num(out, v.gid)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "pid")
    out += b": "
    num(out, v.pid)
    if v.key:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "key")
        out += b": "
        esc(out, v.key)
    if v.mac:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "mac")
        out += b": "
        esc(out, v.mac)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_record(out, v, depth):
    if type(v.schema) is not int: raise Refusal("wrong_type", 0)
    if v.schema != 1: raise Refusal("bad_schema", 0)
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "schema")
    out += b": "
    num(out, v.schema)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "time")
    out += b": "
    esc(out, _write_timestamp(v.time))
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "level")
    out += b": "
    num(out, v.level)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "msg")
    out += b": "
    esc(out, v.msg)
    if v.identity:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "identity")
        out += b": "
        enc_list(out, v.identity, depth + 1, enc_attestation)
    if v.job:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "job")
        out += b": "
        esc(out, v.job)
    if v.attrs:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "attrs")
        out += b": "
        strmap(out, v.attrs, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_page(out, v, depth):
    if type(v.outcome) is not str: raise Refusal("wrong_type",0)
    if v.outcome != "page" and v.outcome != "gap" and v.outcome != "unavailable" and v.outcome != "invalid_request" and v.outcome != "record_too_large" and v.outcome != "corrupt" and v.outcome != "unsupported": raise Refusal("bad_enum",0)
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "outcome")
    out += b": "
    esc(out, v.outcome)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "records")
    out += b": "
    enc_list(out, v.records, depth + 1, enc_record)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "next")
    out += b": "
    esc(out, v.next)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "at_end")
    out += b": "
    out += b"true" if v.at_end else b"false"
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oasinkwritearguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "record")
    out += b": "
    enc_record(out, v.record, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oahistoryreaderreadarguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "cursor")
    out += b": "
    esc(out, v.cursor)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "max_records")
    out += b": "
    num(out, v.max_records)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "max_bytes")
    out += b": "
    num(out, v.max_bytes)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oahistoryobserverobservearguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "cursor")
    out += b": "
    esc(out, v.cursor)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "max_records")
    out += b": "
    num(out, v.max_records)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "max_bytes")
    out += b": "
    num(out, v.max_bytes)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "wait_ms")
    out += b": "
    num(out, v.wait_ms)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaserviceframe(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "version")
    out += b": "
    num(out, v.version)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "service")
    out += b": "
    esc(out, v.service)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "method")
    out += b": "
    esc(out, v.method)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "arguments")
    out += b": "
    out += v.arguments.encode("utf-8") if isinstance(v.arguments, str) else v.arguments
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaservicereply(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "version")
    out += b": "
    num(out, v.version)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "service")
    out += b": "
    esc(out, v.service)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "method")
    out += b": "
    esc(out, v.method)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "ok")
    out += b": "
    out += b"true" if v.ok else b"false"
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "payload")
    out += b": "
    out += v.payload.encode("utf-8") if isinstance(v.payload, str) else v.payload
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaserviceerror(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "code")
    out += b": "
    esc(out, v.code)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "message")
    out += b": "
    esc(out, v.message)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oahistoryreaderreadresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_page(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oahistoryobserverobserveresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_page(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def encode(v):
    out = bytearray()
    enc_record(out, v, 0)
    out += b"\n"
    return bytes(out)


_QUOTE, _BACKSLASH, _COLON, _COMMA = 0x22, 0x5C, 0x3A, 0x2C
_LBRACE, _RBRACE, _LBRACK, _RBRACK = 0x7B, 0x7D, 0x5B, 0x5D
_MINUS, _ZERO, _NINE, _DOT, _LOWER_U, _LOWER_N = 0x2D, 0x30, 0x39, 0x2E, 0x75, 0x6E
_UNESCAPE = {0x22: 0x22, 0x5C: 0x5C, 0x2F: 0x2F, 0x62: 0x08,
             0x66: 0x0C, 0x6E: 0x0A, 0x72: 0x0D, 0x74: 0x09}
_DEPTH_LIMIT = 64
_I64_DIGITS = 19


class Refusal(ValueError):
    def __init__(self, word, offset):
        super().__init__("refused: %s at byte %d" % (word, offset))
        self.word = word
        self.offset = offset


class _Reader:
    __slots__ = ("buf", "pos", "depth")

    def __init__(self, buf):
        self.buf = buf
        self.pos = 0
        self.depth = 0

    def refuse(self, word):
        return Refusal(word, self.pos)

    def at(self):
        return self.buf[self.pos] if self.pos < len(self.buf) else 0

    def ws(self):
        while self.pos < len(self.buf) and self.buf[self.pos] in _WS:
            self.pos += 1

    def enter(self):
        self.depth += 1
        if self.depth > _DEPTH_LIMIT:
            raise self.refuse("depth_exceeded")

    def digit(self):
        return _ZERO <= self.at() <= _NINE

    def string(self):
        if self.at() != _QUOTE:
            raise self.refuse("wrong_type")
        self.pos += 1
        out = bytearray()
        while True:
            if self.pos >= len(self.buf):
                raise self.refuse("malformed")
            c = self.buf[self.pos]
            if c == _QUOTE:
                self.pos += 1
                try:
                    return out.decode("utf-8")
                except UnicodeDecodeError:
                    raise self.refuse("bad_string") from None
            if c < 0x20:
                raise self.refuse("bad_string")
            if c == _BACKSLASH:
                self.escape(out)
            else:
                out.append(c)
                self.pos += 1

    def escape(self, out):
        self.pos += 1
        if self.pos >= len(self.buf):
            raise self.refuse("malformed")
        c = self.buf[self.pos]
        self.pos += 1
        plain = _UNESCAPE.get(c)
        if plain is not None:
            out.append(plain)
            return
        if c != _LOWER_U:
            raise self.refuse("bad_string")
        u = self.hex4()
        if 0xDC00 <= u <= 0xDFFF:
            raise self.refuse("bad_string")
        if 0xD800 <= u <= 0xDBFF:
            if (self.pos + 1 >= len(self.buf) or self.buf[self.pos] != _BACKSLASH
                    or self.buf[self.pos + 1] != _LOWER_U):
                raise self.refuse("bad_string")
            self.pos += 2
            low = self.hex4()
            if not 0xDC00 <= low <= 0xDFFF:
                raise self.refuse("bad_string")
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00)
        out += chr(u).encode("utf-8")

    def hex4(self):
        if self.pos + 4 > len(self.buf):
            raise self.refuse("bad_string")
        u = 0
        for i in range(4):
            c = self.buf[self.pos + i]
            if _ZERO <= c <= _NINE:
                u = u << 4 | (c - _ZERO)
            elif 0x61 <= c <= 0x66:
                u = u << 4 | (c - 0x61 + 10)
            elif 0x41 <= c <= 0x46:
                u = u << 4 | (c - 0x41 + 10)
            else:
                raise self.refuse("bad_string")
        self.pos += 4
        return u

    def integer(self, low, high):
        c = self.at()
        if c != _MINUS and not _ZERO <= c <= _NINE:
            raise self.refuse("wrong_type")
        negative = c == _MINUS
        if negative:
            self.pos += 1
        if not self.digit():
            raise self.refuse("malformed")
        start = self.pos
        if self.at() == _ZERO:
            self.pos += 1
        else:
            while self.digit():
                self.pos += 1
        if self.at() in (_DOT, 0x65, 0x45) or self.digit():
            raise self.refuse("number_spelling")
        if self.pos - start > _I64_DIGITS:
            raise self.refuse("number_spelling")
        n = int(self.buf[start:self.pos])
        if negative:
            if n == 0:
                raise self.refuse("number_spelling")
            n = -n
        if n < low or n > high:
            raise self.refuse("number_spelling")
        return n

    def boolean(self):
        if self.at() == 0x74:
            self.literal(b"true")
            return True
        if self.at() == 0x66:
            self.literal(b"false")
            return False
        raise self.refuse("wrong_type")

    def literal(self, word):
        if self.buf[self.pos:self.pos + len(word)] != word:
            raise self.refuse("malformed")
        self.pos += len(word)

    def str_list(self):
        if self.at() != _LBRACK:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = []
        self.ws()
        if self.at() != _RBRACK:
            while True:
                self.ws()
                out.append(self.string())
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACK:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.raw_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_value(self):
        start = self.pos
        self.skip_value()
        return self.buf[start:self.pos]

    def skip_value(self):
        c = self.at()
        if c == _QUOTE:
            self.skip_string()
        elif c in (_LBRACE, _LBRACK):
            self.skip_container()
        elif c == 0x74:
            self.literal(b"true")
        elif c == 0x66:
            self.literal(b"false")
        elif c == 0x6E:
            self.literal(b"null")
        elif c == _MINUS or _ZERO <= c <= _NINE:
            self.skip_number()
        else:
            raise self.refuse("malformed")

    # An opaque value is validated and carried, never interpreted. Its syntax is
    # the record's own — the same string reader, so an escape, a control byte or
    # a lone surrogate is judged identically at any depth — and what it is free
    # to spell, it keeps: the bytes between these two offsets are what a writer
    # re-emits. A number is walked, never converted, so a value no host type
    # holds survives the reader that carried it.
    def skip_string(self):
        self.string()

    def some_digits(self):
        n = 0
        while _ZERO <= self.at() <= _NINE:
            self.pos += 1
            n += 1
        if n == 0:
            raise self.refuse("number_spelling")

    def skip_number(self):
        if self.at() == _MINUS:
            self.pos += 1
        c = self.at()
        if c == _ZERO:
            self.pos += 1
        elif _ZERO < c <= _NINE:
            while _ZERO <= self.at() <= _NINE:
                self.pos += 1
        else:
            raise self.refuse("number_spelling")
        if self.at() == _DOT:
            self.pos += 1
            self.some_digits()
        if self.at() in (0x65, 0x45):
            self.pos += 1
            if self.at() in (0x2B, _MINUS):
                self.pos += 1
            self.some_digits()

    def skip_container(self):
        opener = self.at()
        shut = _RBRACE if opener == _LBRACE else _RBRACK
        self.enter()
        self.pos += 1
        self.ws()
        seen = set()
        if self.at() != shut:
            while True:
                self.ws()
                if opener == _LBRACE:
                    if self.at() != _QUOTE:
                        raise self.refuse("malformed")
                    k = self.string()
                    self.ws()
                    if self.at() != _COLON:
                        raise self.refuse("malformed")
                    self.pos += 1
                    self.ws()
                self.skip_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != shut:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1

    def str_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.string()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out


def _decode_list(r, elem):
    if r.at() != _LBRACK:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    out = []
    r.ws()
    if r.at() != _RBRACK:
        while True:
            r.ws()
            out.append(elem(r))
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACK:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    return out


def _digits(s, i, n):
    return len(s) >= i + n and all("0" <= s[i + k] <= "9" for k in range(n))


def _date_part(s):
    return (len(s) >= 19 and _digits(s, 0, 4) and s[4] == "-" and _digits(s, 5, 2)
            and s[7] == "-" and _digits(s, 8, 2) and _digits(s, 11, 2) and s[13] == ":"
            and _digits(s, 14, 2) and s[16] == ":" and _digits(s, 17, 2))


def _lexical_timestamp(s):
    """[DEF-G1] rfc3339-wide: what a reader accepts. Any fraction of one to nine
    digits or none, either case of the separators, and a numeric offset."""
    if not _date_part(s) or s[10] not in "Tt":
        return False
    i = 19
    if i < len(s) and s[i] == ".":
        i += 1
        start = i
        while i < len(s) and "0" <= s[i] <= "9":
            i += 1
        if not 1 <= i - start <= 9:
            return False
    if i >= len(s):
        return False
    if s[i] in "Zz":
        return i + 1 == len(s)
    if s[i] not in "+-":
        return False
    return len(s) == i + 6 and _digits(s, i + 1, 2) and s[i + 3] == ":" and _digits(s, i + 4, 2)


def micros_timestamp(s):
    """[DEF-G2] rfc3339-micros: what a writer emits. Exactly six fractional
    digits, upper-case separators, UTC."""
    return len(s) == 27 and _normalized_timestamp(s) == s


def _read_timestamp(r):
    at = r.pos
    s = r.string()
    if not wide_timestamp(s):
        r.pos = at
        raise r.refuse("bad_timestamp")
    return s

def _timestamp_days(y, m):
    if m == 2:
        return 29 if y % 4 == 0 and (y % 100 != 0 or y % 400 == 0) else 28
    return 30 if m in (4, 6, 9, 11) else 31


def _normalized_timestamp(s):
    if not _lexical_timestamp(s):
        return ""
    y, m, d = int(s[:4]), int(s[5:7]), int(s[8:10])
    h, minute, sec = int(s[11:13]), int(s[14:16]), int(s[17:19])
    if not 1 <= m <= 12 or not 1 <= d <= _timestamp_days(y, m) or h > 23 or minute > 59 or sec > 59:
        return ""
    i, fraction = 19, ""
    if s[i] == ".":
        i += 1
        start = i
        while "0" <= s[i] <= "9":
            i += 1
        fraction = s[start:i]
    total = h * 60 + minute
    if s[i] in "+-":
        oh, om = int(s[i+1:i+3]), int(s[i+4:i+6])
        if oh > 23 or om > 59:
            return ""
        offset = oh * 60 + om
        total += -offset if s[i] == "+" else offset
    if total < 0:
        total += 1440
        d -= 1
    elif total >= 1440:
        total -= 1440
        d += 1
    if d == 0:
        m -= 1
        if m == 0:
            y, m = y - 1, 12
        d = _timestamp_days(y, m)
    if d > _timestamp_days(y, m):
        d, m = 1, m + 1
        if m == 13:
            y, m = y + 1, 1
    if not 0 <= y <= 9999:
        return ""
    return "%04d-%02d-%02dT%02d:%02d:%02d.%sZ" % (y, m, d, total // 60, total % 60, sec, (fraction + "000000")[:6])


def wide_timestamp(s):
    return bool(_normalized_timestamp(s))


def _write_timestamp(s):
    result = _normalized_timestamp(s)
    if not result:
        raise Refusal("bad_timestamp", 0)
    return result


def _decode_attestation(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Attestation()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "by":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.by = r.string()
            elif key == "verified":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.verified = r.boolean()
            elif key == "hop":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.hop = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "program":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.program = r.string()
            elif key == "host":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.host = r.string()
            elif key == "user":
                if seen & 32:
                    raise r.refuse("duplicate_field")
                seen |= 32
                v.user = r.string()
            elif key == "exe":
                if seen & 64:
                    raise r.refuse("duplicate_field")
                seen |= 64
                v.exe = r.string()
            elif key == "uid":
                if seen & 128:
                    raise r.refuse("duplicate_field")
                seen |= 128
                v.uid = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "gid":
                if seen & 256:
                    raise r.refuse("duplicate_field")
                seen |= 256
                v.gid = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "pid":
                if seen & 512:
                    raise r.refuse("duplicate_field")
                seen |= 512
                v.pid = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "key":
                if seen & 1024:
                    raise r.refuse("duplicate_field")
                seen |= 1024
                v.key = r.string()
            elif key == "mac":
                if seen & 2048:
                    raise r.refuse("duplicate_field")
                seen |= 2048
                v.mac = r.string()
            else:
                r.skip_value()
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 903 != 903:
        raise r.refuse("missing_field")
    return v


def _decode_record(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Record()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "schema":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.schema = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "time":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.time = _read_timestamp(r)
            elif key == "level":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.level = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "msg":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.msg = r.string()
            elif key == "identity":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.identity = _decode_list(r, _decode_attestation)
            elif key == "job":
                if seen & 32:
                    raise r.refuse("duplicate_field")
                seen |= 32
                v.job = r.string()
            elif key == "attrs":
                if seen & 64:
                    raise r.refuse("duplicate_field")
                seen |= 64
                v.attrs = r.str_map()
            else:
                r.skip_value()
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    if v.schema != 1: raise r.refuse("bad_schema")
    return v


def _decode_page(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Page()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "outcome":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.outcome = r.string()
            elif key == "records":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.records = _decode_list(r, _decode_record)
            elif key == "next":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.next = r.string()
            elif key == "at_end":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.at_end = r.boolean()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    if v.outcome != "page" and v.outcome != "gap" and v.outcome != "unavailable" and v.outcome != "invalid_request" and v.outcome != "record_too_large" and v.outcome != "corrupt" and v.outcome != "unsupported": raise r.refuse("bad_enum")
    return v


def _decode_oasinkwritearguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OASinkWriteArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "record":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.record = _decode_record(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oahistoryreaderreadarguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAHistoryReaderReadArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "cursor":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.cursor = r.string()
            elif key == "max_records":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.max_records = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "max_bytes":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.max_bytes = r.integer(-9223372036854775808, 9223372036854775807)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 7 != 7:
        raise r.refuse("missing_field")
    return v


def _decode_oahistoryobserverobservearguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAHistoryObserverObserveArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "cursor":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.cursor = r.string()
            elif key == "max_records":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.max_records = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "max_bytes":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.max_bytes = r.integer(-9223372036854775808, 9223372036854775807)
            elif key == "wait_ms":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.wait_ms = r.integer(-9223372036854775808, 9223372036854775807)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    return v


def _decode_oaserviceframe(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAServiceFrame()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "arguments":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.arguments = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    return v


def _decode_oaservicereply(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAServiceReply()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "ok":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.ok = r.boolean()
            elif key == "payload":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.payload = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 31 != 31:
        raise r.refuse("missing_field")
    return v


def _decode_oaserviceerror(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAServiceError()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "code":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.code = r.string()
            elif key == "message":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.message = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_oahistoryreaderreadresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAHistoryReaderReadResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_page(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oahistoryobserverobserveresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAHistoryObserverObserveResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_page(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def decode(data):
    r = _Reader(bytes(data))
    r.ws()
    v = _decode_record(r)
    r.ws()
    if r.pos < len(r.buf):
        raise r.refuse("trailing_bytes")
    return v


# REFUSALS is in the order two of them are chosen between.

REFUSALS = ["malformed", "bad_string", "number_spelling", "wrong_type", "bad_timestamp", "depth_exceeded", "duplicate_field", "unknown_field", "missing_field", "bad_schema", "bad_enum", "trailing_bytes"]


def refusal_rank(word):
    return REFUSALS.index(word) if word in REFUSALS else -1


class DispatchError(ValueError):
    def __init__(self, code):
        super().__init__(code)
        self.code = code


def _service_decode(decoder, frame, depth=0):
    if not isinstance(frame, (bytes, bytearray, memoryview)):
        raise TypeError("transport frame must be bytes")
    r = _Reader(bytes(frame))
    r.depth = depth
    r.ws()
    value = decoder(r)
    r.ws()
    if r.pos != len(r.buf):
        raise r.refuse("trailing_bytes")
    return value


def _service_encode(encoder, value, depth):
    out = bytearray()
    try:
        encoder(out, value, depth)
    except UnicodeError:
        raise Refusal("bad_string", 0) from None
    return bytes(out)


def _service_request(service, method, arguments):
    v = OAServiceFrame(version=1, service=service, method=method, arguments=arguments)
    frame = _service_encode(enc_oaserviceframe, v, 0)
    _service_decode(_decode_oaserviceframe, frame)
    return frame


def _service_check(kind, value, depth=0):
    # Python coercions must not silently change typed service arguments.
    if depth >= _DEPTH_LIMIT and (kind.startswith(("list<", "map<")) or kind in _SERVICE_RECORDS):
        raise Refusal("depth_exceeded", 0)
    if kind == "string":
        valid = type(value) is str
    elif kind in ("i32", "i64"):
        valid = type(value) is int
        if valid:
            limit = 1 << (31 if kind == "i32" else 63)
            if not -limit <= value < limit:
                raise Refusal("number_spelling", 0)
    elif kind == "bool":
        valid = type(value) is bool
    elif kind == "json":
        valid = isinstance(value, (str, bytes, bytearray, memoryview))
    elif kind.startswith("list<"):
        valid = type(value) is list
        if valid:
            for item in value:
                _service_check(kind[5:-1], item, depth + 1)
    elif kind.startswith("map<string,"):
        valid = type(value) is dict
        if valid:
            for key, item in value.items():
                _service_check("string", key, depth + 1)
                _service_check(kind[11:-1], item, depth + 1)
    else:
        cls, fields = _SERVICE_RECORDS[kind]
        valid = isinstance(value, cls)
        if valid:
            for name, field_kind, omit in fields:
                if not hasattr(value, name):
                    raise Refusal("missing_field", 0)
                item = getattr(value, name)
                if omit == "absent" and item is None:
                    continue
                _service_check(field_kind, item, depth + 1)
    if not valid:
        raise Refusal("wrong_type", 0)

def service_name(frame):
    """Validate envelope/version for routing; dispatchers validate typed arguments."""
    value = _service_decode(_decode_oaserviceframe, frame)
    if value.version != 1:
        raise DispatchError("unknown_version")
    return value.service



class ServiceError(Exception):
    def __init__(self, code, message=""):
        super().__init__(message if message else code)
        self.code = code
        self.message = message


def _service_response(frame, service, method):
    reply = _service_decode(_decode_oaservicereply, frame)
    if reply.version != 1:
        raise DispatchError("unknown_version")
    if reply.service != service or reply.method != method:
        raise DispatchError("mismatched_response")
    if not reply.ok:
        error = _service_decode(_decode_oaserviceerror, reply.payload, 1)
        if not error.code:
            raise DispatchError("invalid_error")
        raise ServiceError(error.code, error.message)
    return reply.payload

_SERVICE_RECORDS = {
    "Attestation": (Attestation, [("by","string","never"),("verified","bool","never"),("hop","i64","never"),("program","string","zero"),("host","string","zero"),("user","string","zero"),("exe","string","zero"),("uid","i64","never"),("gid","i64","never"),("pid","i64","never"),("key","string","zero"),("mac","string","zero"),]),
    "Record": (Record, [("schema","i64","never"),("time","string","never"),("level","i64","never"),("msg","string","never"),("identity","list<Attestation>","zero"),("job","string","zero"),("attrs","map<string,string>","zero"),]),
    "Page": (Page, [("outcome","string","never"),("records","list<Record>","never"),("next","string","never"),("at_end","bool","never"),]),
    "OASinkWriteArguments": (OASinkWriteArguments, [("record","Record","never"),]),
    "OAHistoryReaderReadArguments": (OAHistoryReaderReadArguments, [("cursor","string","never"),("max_records","i64","never"),("max_bytes","i64","never"),]),
    "OAHistoryObserverObserveArguments": (OAHistoryObserverObserveArguments, [("cursor","string","never"),("max_records","i64","never"),("max_bytes","i64","never"),("wait_ms","i64","never"),]),
    "OAServiceFrame": (OAServiceFrame, [("version","i32","never"),("service","string","never"),("method","string","never"),("arguments","json","never"),]),
    "OAServiceReply": (OAServiceReply, [("version","i32","never"),("service","string","never"),("method","string","never"),("ok","bool","never"),("payload","json","never"),]),
    "OAServiceError": (OAServiceError, [("code","string","never"),("message","string","never"),]),
    "OAHistoryReaderReadResult": (OAHistoryReaderReadResult, [("value","Page","never"),]),
    "OAHistoryObserverObserveResult": (OAHistoryObserverObserveResult, [("value","Page","never"),]),
}


class Sink:
    __doc__ = "A sink for structured log records across a service boundary."
    def Write(self, record: "Record") -> "None":
        raise NotImplementedError


class SinkClient(Sink):
    def __init__(self, transport):
        self._transport = transport

    def Write(self, record: "Record") -> "None":
        _service_check("Record", record)
        _oa_args = OASinkWriteArguments()
        _oa_args.record = record
        _oa_arguments = _service_encode(enc_oasinkwritearguments, _oa_args, 1)
        _service_decode(_decode_oasinkwritearguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.logging/sink@1", "Write", _oa_arguments)
        self._transport.write_frame(_oa_request)
        return None


class HistoryReader:
    __doc__ = "Authorized bounded access to retained logging history. Applications receive records and opaque cursors; history location and retention belong to the provider."
    def Read(self, cursor: "str", max_records: "int", max_bytes: "int") -> "Page":
        raise NotImplementedError


class HistoryReaderClient(HistoryReader):
    def __init__(self, transport):
        self._transport = transport

    def Read(self, cursor: "str", max_records: "int", max_bytes: "int") -> "Page":
        _service_check("string", cursor)
        _service_check("i64", max_records)
        _service_check("i64", max_bytes)
        _oa_args = OAHistoryReaderReadArguments()
        _oa_args.cursor = cursor
        _oa_args.max_records = max_records
        _oa_args.max_bytes = max_bytes
        _oa_arguments = _service_encode(enc_oahistoryreaderreadarguments, _oa_args, 1)
        _service_decode(_decode_oahistoryreaderreadarguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.logging/reader@1", "Read", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.logging/reader@1", "Read")
        _oa_result = _service_decode(_decode_oahistoryreaderreadresult, _oa_payload, 1)
        return _oa_result.value


class HistoryObserver:
    __doc__ = "Authorized bounded long-poll history observation with provider-owned notifications."
    def Observe(self, cursor: "str", max_records: "int", max_bytes: "int", wait_ms: "int") -> "Page":
        raise NotImplementedError


class HistoryObserverClient(HistoryObserver):
    def __init__(self, transport):
        self._transport = transport

    def Observe(self, cursor: "str", max_records: "int", max_bytes: "int", wait_ms: "int") -> "Page":
        _service_check("string", cursor)
        _service_check("i64", max_records)
        _service_check("i64", max_bytes)
        _service_check("i64", wait_ms)
        _oa_args = OAHistoryObserverObserveArguments()
        _oa_args.cursor = cursor
        _oa_args.max_records = max_records
        _oa_args.max_bytes = max_bytes
        _oa_args.wait_ms = wait_ms
        _oa_arguments = _service_encode(enc_oahistoryobserverobservearguments, _oa_args, 1)
        _service_decode(_decode_oahistoryobserverobservearguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.logging/observer@1", "Observe", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.logging/observer@1", "Observe")
        _oa_result = _service_decode(_decode_oahistoryobserverobserveresult, _oa_payload, 1)
        return _oa_result.value
