// Code generated by abstraction-idl from abstraction-logging/logging.thrift. DO NOT EDIT.

const HEX = "0123456789abcdef";
const ENC = new TextEncoder();
const SHORT = { 0x22: '\\"', 0x5c: "\\\\", 0x08: "\\b", 0x0c: "\\f", 0x0a: "\\n", 0x0d: "\\r", 0x09: "\\t" };

export class Out {
  constructor() { this.b = []; }
  byte(c) { this.b.push(c); }
  ascii(s) { for (let i = 0; i < s.length; i++) this.b.push(s.charCodeAt(i)); }
  bytes() { return Uint8Array.from(this.b); }
}

function escByte(out, c) {
  const short = SHORT[c];
  if (short !== undefined) out.ascii(short);
  else if (c < 0x20) out.ascii("\\u00" + HEX[c >> 4] + HEX[c & 0xf]);
  else out.byte(c);
}

// Every integer the definition calls i64 is a BigInt here, because Number
// rounds above 2^53 and two values in the conformance record are i64 extremes.
export function num(out, n) { out.ascii(BigInt(n).toString()); }

export function pad(out, depth) { for (let i = 0; i < depth * 2; i++) out.byte(0x20); }

export function strs(out, v, depth) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    esc(out, v[i]);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

const isWs = (c) => c === 0x20 || c === 0x09 || c === 0x0a || c === 0x0d;

export function raw(out, s, depth) {
  const b = typeof s === "string" ? ENC.encode(s) : s;
  let i = 0;
  while (i < b.length) {
    const c = b[i];
    if (isWs(c)) { i++; continue; }
    if (c === 0x22) {
      let j = i + 1;
      while (j < b.length) {
        if (b[j] === 0x5c) { j += 2; continue; }
        if (b[j] === 0x22) { j++; break; }
        j++;
      }
      for (let k = i; k < j; k++) out.byte(b[k]);
      i = j;
    } else if (c === 0x7b || c === 0x5b) {
      out.byte(c);
      i++;
      let j = i;
      while (j < b.length && isWs(b[j])) j++;
      if (j < b.length && (b[j] === 0x7d || b[j] === 0x5d)) { out.byte(b[j]); i = j + 1; }
      else { depth++; out.byte(0x0a); pad(out, depth); }
    } else if (c === 0x7d || c === 0x5d) {
      depth--;
      out.byte(0x0a);
      pad(out, depth);
      out.byte(c);
      i++;
    } else if (c === 0x2c) {
      out.ascii(",\n");
      pad(out, depth);
      i++;
    } else if (c === 0x3a) {
      out.ascii(": ");
      i++;
    } else {
      out.byte(c);
      i++;
    }
  }
}

// A JavaScript string sorts by UTF-16 code unit, which puts U+1D11E before
// U+FFFD where every other target puts it after. The definition declares UTF-8
// byte order, so the comparison is done on the encoded bytes.
function byteLess(a, b) {
  const x = ENC.encode(a), y = ENC.encode(b);
  const n = Math.min(x.length, y.length);
  for (let i = 0; i < n; i++) if (x[i] !== y[i]) return x[i] - y[i];
  return x.length - y.length;
}

export function rawmap(out, m, depth) {
  const keys = Object.keys(m).sort(byteLess);
  if (keys.length === 0) { out.ascii("{}"); return; }
  out.ascii("{\n");
  for (let i = 0; i < keys.length; i++) {
    pad(out, depth + 1);
    esc(out, keys[i]);
    out.ascii(": ");
    raw(out, m[keys[i]], depth + 1);
    if (i + 1 < keys.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x7d);
}

export function esc(out, s) {
  out.byte(0x22);
  for (const c of ENC.encode(s)) escByte(out, c);
  out.byte(0x22);
}

export function strmap(out, m, depth) {
  const keys = Object.keys(m).sort(byteLess);
  if (keys.length === 0) { out.ascii("{}"); return; }
  out.ascii("{\n");
  for (let i = 0; i < keys.length; i++) {
    pad(out, depth + 1);
    esc(out, keys[i]);
    out.ascii(": ");
    esc(out, m[keys[i]]);
    if (i + 1 < keys.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x7d);
}

export function encList(out, v, depth, enc) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    enc(out, v[i], depth + 1);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

export const PageOutcomeNames = ["page", "gap", "unavailable", "invalid_request", "record_too_large", "corrupt", "unsupported"];
export const PageOutcomeUnknown = "refuse";

export function enc_attestation(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "by");
  out.ascii(": ");
  esc(out, v.by);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "verified");
  out.ascii(": ");
  out.ascii(v.verified ? "true" : "false");
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "hop");
  out.ascii(": ");
  num(out, v.hop);
  if (v.program !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "program");
    out.ascii(": ");
    esc(out, v.program);
  }
  if (v.host !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "host");
    out.ascii(": ");
    esc(out, v.host);
  }
  if (v.user !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "user");
    out.ascii(": ");
    esc(out, v.user);
  }
  if (v.exe !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "exe");
    out.ascii(": ");
    esc(out, v.exe);
  }
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "uid");
  out.ascii(": ");
  num(out, v.uid);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "gid");
  out.ascii(": ");
  num(out, v.gid);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "pid");
  out.ascii(": ");
  num(out, v.pid);
  if (v.key !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "key");
    out.ascii(": ");
    esc(out, v.key);
  }
  if (v.mac !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "mac");
    out.ascii(": ");
    esc(out, v.mac);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_record(out, v, depth) {
  if (v.schema !== 1n) throw new Refusal("bad_schema",0);
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "schema");
  out.ascii(": ");
  num(out, v.schema);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "time");
  out.ascii(": ");
  esc(out, writeTimestamp(v.time));
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "level");
  out.ascii(": ");
  num(out, v.level);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "msg");
  out.ascii(": ");
  esc(out, v.msg);
  if (v.identity.length !== 0) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "identity");
    out.ascii(": ");
    encList(out, v.identity, depth + 1, enc_attestation);
  }
  if (v.job !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "job");
    out.ascii(": ");
    esc(out, v.job);
  }
  if (Object.keys(v.attrs).length !== 0) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "attrs");
    out.ascii(": ");
    strmap(out, v.attrs, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_page(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "page" && v.outcome !== "gap" && v.outcome !== "unavailable" && v.outcome !== "invalid_request" && v.outcome !== "record_too_large" && v.outcome !== "corrupt" && v.outcome !== "unsupported") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "records");
  out.ascii(": ");
  encList(out, v.records, depth + 1, enc_record);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "next");
  out.ascii(": ");
  esc(out, v.next);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "at_end");
  out.ascii(": ");
  out.ascii(v.at_end ? "true" : "false");
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oasinkwritearguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "record");
  out.ascii(": ");
  enc_record(out, v.record, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oahistoryreaderreadarguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "cursor");
  out.ascii(": ");
  esc(out, v.cursor);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "max_records");
  out.ascii(": ");
  num(out, v.max_records);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "max_bytes");
  out.ascii(": ");
  num(out, v.max_bytes);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oahistoryobserverobservearguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "cursor");
  out.ascii(": ");
  esc(out, v.cursor);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "max_records");
  out.ascii(": ");
  num(out, v.max_records);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "max_bytes");
  out.ascii(": ");
  num(out, v.max_bytes);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "wait_ms");
  out.ascii(": ");
  num(out, v.wait_ms);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaserviceframe(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "arguments");
  out.ascii(": ");
  for (const byte of (typeof v.arguments === "string" ? ENC.encode(v.arguments) : v.arguments)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaservicereply(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "ok");
  out.ascii(": ");
  out.ascii(v.ok ? "true" : "false");
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "payload");
  out.ascii(": ");
  for (const byte of (typeof v.payload === "string" ? ENC.encode(v.payload) : v.payload)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oaserviceerror(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "code");
  out.ascii(": ");
  esc(out, v.code);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "message");
  out.ascii(": ");
  esc(out, v.message);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oahistoryreaderreadresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_page(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function enc_oahistoryobserverobserveresult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  enc_page(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function encode(v) {
  const out = new Out();
  enc_record(out, v, 0);
  out.byte(0x0a);
  return out.bytes();
}

// A BOM inside a JSON string is data, not a stream signature.
const DEC = new TextDecoder("utf-8", {ignoreBOM: true});
const DEPTH_LIMIT = 64;
const I64_DIGITS = 19;
const UNESCAPE = { 0x22: 0x22, 0x5c: 0x5c, 0x2f: 0x2f, 0x62: 0x08, 0x66: 0x0c, 0x6e: 0x0a, 0x72: 0x0d, 0x74: 0x09 };

export class Refusal extends Error {
  constructor(word, offset) {
    super("refused: " + word + " at byte " + offset);
    this.name = "Refusal";
    this.word = word;
    this.offset = offset;
  }
}

function appendRune(out, cp) {
  if (cp < 0x80) out.push(cp);
  else if (cp < 0x800) out.push(0xc0 | (cp >> 6), 0x80 | (cp & 0x3f));
  else if (cp < 0x10000) out.push(0xe0 | (cp >> 12), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
  else out.push(0xf0 | (cp >> 18), 0x80 | ((cp >> 12) & 0x3f), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
}

// TextDecoder substitutes U+FFFD for a bad sequence rather than reporting it, so
// the bytes are checked before they are decoded and the refusal says so.
function validUtf8(b) {
  for (let i = 0; i < b.length; ) {
    const c = b[i];
    if (c < 0x80) { i++; continue; }
    let n, cp;
    if (c >> 5 === 0x6) { n = 2; cp = c & 0x1f; }
    else if (c >> 4 === 0xe) { n = 3; cp = c & 0x0f; }
    else if (c >> 3 === 0x1e) { n = 4; cp = c & 0x07; }
    else return false;
    if (i + n > b.length) return false;
    for (let k = 1; k < n; k++) {
      if (b[i + k] >> 6 !== 0x2) return false;
      cp = (cp << 6) | (b[i + k] & 0x3f);
    }
    const lowest = [0, 0, 0x80, 0x800, 0x10000][n];
    if (cp < lowest || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) return false;
    i += n;
  }
  return true;
}

class Reader {
  constructor(buf) { this.buf = buf; this.pos = 0; this.depth = 0; }

  refuse(word) { return new Refusal(word, this.pos); }

  at() { return this.pos < this.buf.length ? this.buf[this.pos] : 0; }

  digit() { const c = this.at(); return c >= 0x30 && c <= 0x39; }

  ws() { while (this.pos < this.buf.length && isWs(this.buf[this.pos])) this.pos++; }

  enter() {
    this.depth++;
    if (this.depth > DEPTH_LIMIT) throw this.refuse("depth_exceeded");
  }

  string() {
    if (this.at() !== 0x22) throw this.refuse("wrong_type");
    this.pos++;
    const out = [];
    for (;;) {
      if (this.pos >= this.buf.length) throw this.refuse("malformed");
      const c = this.buf[this.pos];
      if (c === 0x22) {
        this.pos++;
        const bytes = Uint8Array.from(out);
        if (!validUtf8(bytes)) throw this.refuse("bad_string");
        return DEC.decode(bytes);
      }
      if (c < 0x20) throw this.refuse("bad_string");
      if (c === 0x5c) this.escape(out);
      else { out.push(c); this.pos++; }
    }
  }

  escape(out) {
    this.pos++;
    if (this.pos >= this.buf.length) throw this.refuse("malformed");
    const c = this.buf[this.pos];
    this.pos++;
    const plain = UNESCAPE[c];
    if (plain !== undefined) { out.push(plain); return; }
    if (c !== 0x75) throw this.refuse("bad_string");
    let u = this.hex4();
    if (u >= 0xdc00 && u <= 0xdfff) throw this.refuse("bad_string");
    if (u >= 0xd800 && u <= 0xdbff) {
      if (this.pos + 1 >= this.buf.length || this.buf[this.pos] !== 0x5c || this.buf[this.pos + 1] !== 0x75)
        throw this.refuse("bad_string");
      this.pos += 2;
      const low = this.hex4();
      if (low < 0xdc00 || low > 0xdfff) throw this.refuse("bad_string");
      u = 0x10000 + ((u - 0xd800) << 10) + (low - 0xdc00);
    }
    appendRune(out, u);
  }

  hex4() {
    if (this.pos + 4 > this.buf.length) throw this.refuse("bad_string");
    let u = 0;
    for (let i = 0; i < 4; i++) {
      const c = this.buf[this.pos + i];
      if (c >= 0x30 && c <= 0x39) u = (u << 4) | (c - 0x30);
      else if (c >= 0x61 && c <= 0x66) u = (u << 4) | (c - 0x61 + 10);
      else if (c >= 0x41 && c <= 0x46) u = (u << 4) | (c - 0x41 + 10);
      else throw this.refuse("bad_string");
    }
    this.pos += 4;
    return u;
  }

  integer(low, high) {
    const c = this.at();
    if (c !== 0x2d && (c < 0x30 || c > 0x39)) throw this.refuse("wrong_type");
    const negative = c === 0x2d;
    if (negative) this.pos++;
    if (!this.digit()) throw this.refuse("malformed");
    const start = this.pos;
    if (this.at() === 0x30) this.pos++;
    else while (this.digit()) this.pos++;
    const after = this.at();
    if (after === 0x2e || after === 0x65 || after === 0x45 || this.digit()) throw this.refuse("number_spelling");
    if (this.pos - start > I64_DIGITS) throw this.refuse("number_spelling");
    let n = BigInt(String.fromCharCode(...this.buf.subarray(start, this.pos)));
    if (negative) {
      if (n === 0n) throw this.refuse("number_spelling");
      n = -n;
    }
    if (n < low || n > high) throw this.refuse("number_spelling");
    return n;
  }

  boolean() {
    if (this.at() === 0x74) { this.literal("true"); return true; }
    if (this.at() === 0x66) { this.literal("false"); return false; }
    throw this.refuse("wrong_type");
  }

  literal(word) {
    for (let i = 0; i < word.length; i++)
      if (this.buf[this.pos + i] !== word.charCodeAt(i)) throw this.refuse("malformed");
    this.pos += word.length;
  }

  strList() {
    if (this.at() !== 0x5b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = [];
    this.ws();
    if (this.at() !== 0x5d) {
      for (;;) {
        this.ws();
        out.push(this.string());
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x5d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawMap() {
    if (this.at() !== 0x7b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = Object.create(null);
    this.ws();
    if (this.at() !== 0x7d) {
      for (;;) {
        this.ws();
        if (this.at() !== 0x22) throw this.refuse("malformed");
        const k = this.string();
        this.ws();
        if (this.at() !== 0x3a) throw this.refuse("malformed");
        this.pos++;
        this.ws();
        out[k] = this.rawValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x7d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawValue() {
    const start = this.pos;
    this.skipValue();
    return this.buf.subarray(start, this.pos);
  }

  skipValue() {
    const c = this.at();
    if (c === 0x22) this.skipString();
    else if (c === 0x7b || c === 0x5b) this.skipContainer();
    else if (c === 0x74) this.literal("true");
    else if (c === 0x66) this.literal("false");
    else if (c === 0x6e) this.literal("null");
    else if (c === 0x2d || (c >= 0x30 && c <= 0x39)) this.skipNumber();
    else throw this.refuse("malformed");
  }

  // An opaque value is validated and carried, never interpreted. Its syntax is
  // the record's own — the same string reader, so an escape, a control byte or a
  // lone surrogate is judged identically at any depth — and what it is free to
  // spell, it keeps: the bytes between these two offsets are what a writer
  // re-emits. A number is walked, never converted, so a value no host type holds
  // survives the reader that carried it.
  skipString() {
    this.string();
  }

  someDigits() {
    let n = 0;
    while (this.at() >= 0x30 && this.at() <= 0x39) { this.pos++; n++; }
    if (n === 0) throw this.refuse("number_spelling");
  }

  skipNumber() {
    if (this.at() === 0x2d) this.pos++;
    const c = this.at();
    if (c === 0x30) this.pos++;
    else if (c > 0x30 && c <= 0x39) { while (this.at() >= 0x30 && this.at() <= 0x39) this.pos++; }
    else throw this.refuse("number_spelling");
    if (this.at() === 0x2e) { this.pos++; this.someDigits(); }
    if (this.at() === 0x65 || this.at() === 0x45) {
      this.pos++;
      if (this.at() === 0x2b || this.at() === 0x2d) this.pos++;
      this.someDigits();
    }
  }

  skipContainer() {
    const opener = this.at();
    const shut = opener === 0x7b ? 0x7d : 0x5d;
    this.enter();
    this.pos++;
    this.ws();
    const seen = new Set();
    if (this.at() !== shut) {
      for (;;) {
        this.ws();
        if (opener === 0x7b) {
          if (this.at() !== 0x22) throw this.refuse("malformed");
          const k = this.string();
          this.ws();
          if (this.at() !== 0x3a) throw this.refuse("malformed");
          this.pos++;
          this.ws();
        }
        this.skipValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== shut) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
  }
}

function strMap(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const out = Object.create(null);
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const k = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      out[k] = r.string();
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return out;
}

function decodeList(r, elem) {
  if (r.at() !== 0x5b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const out = [];
  r.ws();
  if (r.at() !== 0x5d) {
    for (;;) {
      r.ws();
      out.push(elem(r));
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x5d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return out;
}

const isDigits = (s, i, n) => {
  if (s.length < i + n) return false;
  for (let k = 0; k < n; k++) if (s[i + k] < "0" || s[i + k] > "9") return false;
  return true;
};

const datePart = (s) =>
  s.length >= 19 && isDigits(s, 0, 4) && s[4] === "-" && isDigits(s, 5, 2) && s[7] === "-" &&
  isDigits(s, 8, 2) && isDigits(s, 11, 2) && s[13] === ":" && isDigits(s, 14, 2) && s[16] === ":" &&
  isDigits(s, 17, 2);

// [DEF-G1] rfc3339-wide: what a reader accepts. Any fraction of one to nine
// digits or none, either case of the separators, and a numeric offset.
function lexicalTimestamp(s) {
  if (!datePart(s) || (s[10] !== "T" && s[10] !== "t")) return false;
  let i = 19;
  if (i < s.length && s[i] === ".") {
    i++;
    const start = i;
    while (i < s.length && s[i] >= "0" && s[i] <= "9") i++;
    if (i - start < 1 || i - start > 9) return false;
  }
  if (i >= s.length) return false;
  if (s[i] === "Z" || s[i] === "z") return i + 1 === s.length;
  if (s[i] !== "+" && s[i] !== "-") return false;
  return s.length === i + 6 && isDigits(s, i + 1, 2) && s[i + 3] === ":" && isDigits(s, i + 4, 2);
}

// [DEF-G2] rfc3339-micros: what a writer emits. Exactly six fractional digits,
// upper-case separators, UTC.
export function microsTimestamp(s) {
  return s.length === 27 && normalizedTimestamp(s) === s;
}

function readTimestamp(r) {
  const at = r.pos;
  const s = r.string();
  if (!wideTimestamp(s)) {
    r.pos = at;
    throw r.refuse("bad_timestamp");
  }
  return s;
}

function timestampDays(y, m) {
  if (m === 2) return y % 4 === 0 && (y % 100 !== 0 || y % 400 === 0) ? 29 : 28;
  return [4, 6, 9, 11].includes(m) ? 30 : 31;
}
function normalizedTimestamp(s) {
  if (!lexicalTimestamp(s)) return "";
  let y=Number(s.slice(0,4)), m=Number(s.slice(5,7)), d=Number(s.slice(8,10));
  const h=Number(s.slice(11,13)), minute=Number(s.slice(14,16)), sec=Number(s.slice(17,19));
  if (m<1 || m>12 || d<1 || d>timestampDays(y,m) || h>23 || minute>59 || sec>59) return "";
  let i=19, fraction="";
  if (s[i]===".") { const start=++i; while(s[i]>="0" && s[i]<="9") i++; fraction=s.slice(start,i); }
  let total=h*60+minute;
  if(s[i]==="+" || s[i]==="-") {
    const oh=Number(s.slice(i+1,i+3)), om=Number(s.slice(i+4,i+6));
    if(oh>23 || om>59) return "";
    total += (s[i]==="+" ? -1 : 1)*(oh*60+om);
  }
  if(total<0) {total+=1440; d--;} else if(total>=1440) {total-=1440; d++;}
  if(d===0) {m--; if(m===0) {y--; m=12;} d=timestampDays(y,m);}
  if(d>timestampDays(y,m)) {d=1; m++; if(m===13) {y++; m=1;}}
  if(y<0 || y>9999) return "";
  const pad=(n,w)=>String(n).padStart(w,"0");
  return pad(y,4)+"-"+pad(m,2)+"-"+pad(d,2)+"T"+pad(Math.floor(total/60),2)+":"+pad(total%60,2)+":"+pad(sec,2)+"."+(fraction+"000000").slice(0,6)+"Z";
}
export function wideTimestamp(s) { return normalizedTimestamp(s)!==""; }
function writeTimestamp(s) {
  const result=normalizedTimestamp(s);
  if(result==="") throw new Refusal("bad_timestamp",0);
  return result;
}

// One hop of the provenance chain. program is the name a party gives itself and
// appears on the writer's self claim. exe is the executable path the attesting
// mechanism resolved for the party it established; a receiving service's stamp
// sets exe and leaves program empty. user is the account name or Windows SID;
// uid and gid are -1 where unestablished.
export function newAttestation() {
  return { by: "", verified: false, hop: 0n, program: "", host: "", user: "", exe: "", uid: 0n, gid: 0n, pid: 0n, key: "", mac: "" };
}

export function newRecord() {
  return { schema: 0n, time: "", level: 0n, msg: "", identity: [], job: "", attrs: {} };
}

// A bounded page in provider append order. next is an opaque continuation bound
// to this history instance. at_end means the observed end during this call;
// later records may appear. Refusals contain no records and never advance a
// supplied cursor. gap requires an explicit restart with empty cursor; it never
// silently restarts a stream.
export function newPage() {
  return { outcome: "", records: [], next: "", at_end: false };
}

export function newOASinkWriteArguments() {
  return { record: newRecord() };
}

export function newOAHistoryReaderReadArguments() {
  return { cursor: "", max_records: 0n, max_bytes: 0n };
}

export function newOAHistoryObserverObserveArguments() {
  return { cursor: "", max_records: 0n, max_bytes: 0n, wait_ms: 0n };
}

export function newOAServiceFrame() {
  return { version: 0, service: "", method: "", arguments: "" };
}

export function newOAServiceReply() {
  return { version: 0, service: "", method: "", ok: false, payload: "" };
}

export function newOAServiceError() {
  return { code: "", message: "" };
}

export function newOAHistoryReaderReadResult() {
  return { value: newPage() };
}

export function newOAHistoryObserverObserveResult() {
  return { value: newPage() };
}

function decode_attestation(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newAttestation();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "by") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.by = r.string();
      } else if (key === "verified") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.verified = r.boolean();
      } else if (key === "hop") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.hop = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "program") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.program = r.string();
      } else if (key === "host") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.host = r.string();
      } else if (key === "user") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.user = r.string();
      } else if (key === "exe") {
        if (seen & 64) throw r.refuse("duplicate_field");
        seen |= 64;
        v.exe = r.string();
      } else if (key === "uid") {
        if (seen & 128) throw r.refuse("duplicate_field");
        seen |= 128;
        v.uid = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "gid") {
        if (seen & 256) throw r.refuse("duplicate_field");
        seen |= 256;
        v.gid = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "pid") {
        if (seen & 512) throw r.refuse("duplicate_field");
        seen |= 512;
        v.pid = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "key") {
        if (seen & 1024) throw r.refuse("duplicate_field");
        seen |= 1024;
        v.key = r.string();
      } else if (key === "mac") {
        if (seen & 2048) throw r.refuse("duplicate_field");
        seen |= 2048;
        v.mac = r.string();
      } else {
        r.skipValue();
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 903) >>> 0) !== 903) throw r.refuse("missing_field");
  return v;
}

function decode_record(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newRecord();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "schema") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.schema = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "time") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.time = readTimestamp(r);
      } else if (key === "level") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.level = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "msg") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.msg = r.string();
      } else if (key === "identity") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.identity = decodeList(r, decode_attestation);
      } else if (key === "job") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.job = r.string();
      } else if (key === "attrs") {
        if (seen & 64) throw r.refuse("duplicate_field");
        seen |= 64;
        v.attrs = strMap(r);
      } else {
        r.skipValue();
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  if (v.schema !== 1n) throw r.refuse("bad_schema");
  return v;
}

function decode_page(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newPage();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "records") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.records = decodeList(r, decode_record);
      } else if (key === "next") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.next = r.string();
      } else if (key === "at_end") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.at_end = r.boolean();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
    if (v.outcome !== "page" && v.outcome !== "gap" && v.outcome !== "unavailable" && v.outcome !== "invalid_request" && v.outcome !== "record_too_large" && v.outcome !== "corrupt" && v.outcome !== "unsupported") { throw r.refuse("bad_enum"); }
  return v;
}

function decode_oasinkwritearguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOASinkWriteArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "record") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.record = decode_record(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oahistoryreaderreadarguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAHistoryReaderReadArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "cursor") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.cursor = r.string();
      } else if (key === "max_records") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.max_records = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "max_bytes") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.max_bytes = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 7) >>> 0) !== 7) throw r.refuse("missing_field");
  return v;
}

function decode_oahistoryobserverobservearguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAHistoryObserverObserveArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "cursor") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.cursor = r.string();
      } else if (key === "max_records") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.max_records = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "max_bytes") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.max_bytes = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "wait_ms") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.wait_ms = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function decode_oaserviceframe(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceFrame();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "arguments") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.arguments = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function decode_oaservicereply(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceReply();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "ok") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.ok = r.boolean();
      } else if (key === "payload") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.payload = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
  return v;
}

function decode_oaserviceerror(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceError();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "code") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.code = r.string();
      } else if (key === "message") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.message = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function decode_oahistoryreaderreadresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAHistoryReaderReadResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_page(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function decode_oahistoryobserverobserveresult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAHistoryObserverObserveResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = decode_page(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

export function decode(data) {
  const r = new Reader(data);
  r.ws();
  const v = decode_record(r);
  r.ws();
  if (r.pos < r.buf.length) throw r.refuse("trailing_bytes");
  return v;
}

// refusals is in the order two of them are chosen between.
export const refusals = ["malformed", "bad_string", "number_spelling", "wrong_type", "bad_timestamp", "depth_exceeded", "duplicate_field", "unknown_field", "missing_field", "bad_schema", "bad_enum", "trailing_bytes"];

export function refusalRank(word) {
  return refusals.indexOf(word);
}

export class DispatchError extends Error {
  constructor(code) { super(code); this.name = "DispatchError"; this.code = code; }
}
export class ServiceError extends Error {
  constructor(code, message = "") { super(message || code); this.name = "ServiceError"; this.code = code; }
}
function _serviceDecode(decoder, frame, depth) {
  const reader = new Reader(typeof frame === "string" ? ENC.encode(frame) : frame);
  reader.depth = depth; reader.ws();
  const value = decoder(reader); reader.ws();
  if (reader.pos !== reader.buf.length) throw reader.refuse("trailing_bytes");
  return value;
}
function _serviceEncode(encoder, value, depth) {
  const out = new Out(); encoder(out, value, depth); return out.bytes();
}
function _serviceCheck(kind, value, depth = 0) {
  if (depth > DEPTH_LIMIT) throw new Refusal("depth_exceeded", 0);
  let valid = false;
  if (kind === "string") {
    valid = typeof value === "string";
    if (valid) for (const ch of value) {
      const cp = ch.codePointAt(0);
      if (cp >= 0xd800 && cp <= 0xdfff) throw new Refusal("bad_string", 0);
    }
  } else if (kind === "i32") {
    valid = typeof value === "number" && Number.isInteger(value) && value >= -2147483648 && value <= 2147483647;
  } else if (kind === "i64") {
    valid = typeof value === "bigint" && value >= -9223372036854775808n && value <= 9223372036854775807n;
  } else if (kind === "bool") valid = typeof value === "boolean";
  else if (kind === "json") {
    valid = typeof value === "string" || value instanceof Uint8Array;
    if (valid) { const r = new Reader(typeof value === "string" ? ENC.encode(value) : value); r.depth = depth; r.ws(); r.rawValue(); r.ws(); if (r.pos !== r.buf.length) throw r.refuse("trailing_bytes"); }
  } else if (kind.startsWith("list<")) {
    valid = Array.isArray(value);
    if (valid) for (const item of value) _serviceCheck(kind.slice(5,-1), item, depth + 1);
  } else if (kind.startsWith("map<string,")) {
    valid = value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [key,item] of Object.entries(value)) { _serviceCheck("string",key,depth+1); _serviceCheck(kind.slice(11,-1),item,depth+1); }
  } else {
    const fields = _serviceRecords[kind];
    valid = fields !== undefined && value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [name,type,omit] of fields) {
      if (!Object.hasOwn(value,name)) throw new Refusal("missing_field",0);
      const item = value[name];
      if (omit === "absent" && item === null) continue;
      _serviceCheck(type,item,depth+1);
    }
  }
  if (!valid) throw new Refusal("wrong_type", 0);
}

const _serviceRecords = Object.create(null);
_serviceRecords["Attestation"] = [["by","string","never"],["verified","bool","never"],["hop","i64","never"],["program","string","zero"],["host","string","zero"],["user","string","zero"],["exe","string","zero"],["uid","i64","never"],["gid","i64","never"],["pid","i64","never"],["key","string","zero"],["mac","string","zero"],];
_serviceRecords["Record"] = [["schema","i64","never"],["time","string","never"],["level","i64","never"],["msg","string","never"],["identity","list<Attestation>","zero"],["job","string","zero"],["attrs","map<string,string>","zero"],];
_serviceRecords["Page"] = [["outcome","string","never"],["records","list<Record>","never"],["next","string","never"],["at_end","bool","never"],];
_serviceRecords["OASinkWriteArguments"] = [["record","Record","never"],];
_serviceRecords["OAHistoryReaderReadArguments"] = [["cursor","string","never"],["max_records","i64","never"],["max_bytes","i64","never"],];
_serviceRecords["OAHistoryObserverObserveArguments"] = [["cursor","string","never"],["max_records","i64","never"],["max_bytes","i64","never"],["wait_ms","i64","never"],];
_serviceRecords["OAServiceFrame"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["arguments","json","never"],];
_serviceRecords["OAServiceReply"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["ok","bool","never"],["payload","json","never"],];
_serviceRecords["OAServiceError"] = [["code","string","never"],["message","string","never"],];
_serviceRecords["OAHistoryReaderReadResult"] = [["value","Page","never"],];
_serviceRecords["OAHistoryObserverObserveResult"] = [["value","Page","never"],];

function _serviceRequest(service, method, argumentsBytes) {
  return _serviceEncode(enc_oaserviceframe, {
    version:1, service, method, arguments:new TextDecoder("utf-8",{fatal:true}).decode(argumentsBytes)
  },0);
}

function _serviceResponse(frame, service, method) {
  if (!(frame instanceof Uint8Array)) throw new TypeError("transport frame must be Uint8Array");
  const reply = _serviceDecode(decode_oaservicereply, frame, 0);
  if (reply.version !== 1) throw new DispatchError("unknown_version");
  if (reply.service !== service || reply.method !== method) throw new DispatchError("mismatched_response");
  if (!reply.ok) {
    const error = _serviceDecode(decode_oaserviceerror, reply.payload, 1);
    if (!error.code) throw new DispatchError("invalid_error");
    throw new ServiceError(error.code, error.message);
  }
  return reply.payload;
}

export class SinkClient {
  constructor(transport) { this._transport = transport; }
  async Write(arg0) {
    const args = newOASinkWriteArguments();
    args["record"] = arg0;
    _serviceCheck("OASinkWriteArguments", args);
    const payload = _serviceEncode(enc_oasinkwritearguments, args, 1);
    _serviceDecode(decode_oasinkwritearguments, payload, 1);
    const request = _serviceRequest("abstraction.logging/sink@1", "Write", payload);
    await this._transport.writeFrame(request);
  }
}
export const SinkService = Object.freeze({wireName:"abstraction.logging/sink@1",Client:SinkClient});

export class HistoryReaderClient {
  constructor(transport) { this._transport = transport; }
  async Read(arg0,arg1,arg2) {
    const args = newOAHistoryReaderReadArguments();
    args["cursor"] = arg0;
    args["max_records"] = arg1;
    args["max_bytes"] = arg2;
    _serviceCheck("OAHistoryReaderReadArguments", args);
    const payload = _serviceEncode(enc_oahistoryreaderreadarguments, args, 1);
    _serviceDecode(decode_oahistoryreaderreadarguments, payload, 1);
    const request = _serviceRequest("abstraction.logging/reader@1", "Read", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.logging/reader@1", "Read");
    const result = _serviceDecode(decode_oahistoryreaderreadresult, reply, 1);
    return result.value;
  }
}
export const HistoryReaderService = Object.freeze({wireName:"abstraction.logging/reader@1",Client:HistoryReaderClient});

export class HistoryObserverClient {
  constructor(transport) { this._transport = transport; }
  async Observe(arg0,arg1,arg2,arg3) {
    const args = newOAHistoryObserverObserveArguments();
    args["cursor"] = arg0;
    args["max_records"] = arg1;
    args["max_bytes"] = arg2;
    args["wait_ms"] = arg3;
    _serviceCheck("OAHistoryObserverObserveArguments", args);
    const payload = _serviceEncode(enc_oahistoryobserverobservearguments, args, 1);
    _serviceDecode(decode_oahistoryobserverobservearguments, payload, 1);
    const request = _serviceRequest("abstraction.logging/observer@1", "Observe", payload);
    const reply = _serviceResponse(await this._transport.exchangeFrame(request), "abstraction.logging/observer@1", "Observe");
    const result = _serviceDecode(decode_oahistoryobserverobserveresult, reply, 1);
    return result.value;
  }
}
export const HistoryObserverService = Object.freeze({wireName:"abstraction.logging/observer@1",Client:HistoryObserverClient});
