// Code generated by abstraction-idl from abstraction-logging/logging.thrift. DO NOT EDIT.

#![allow(dead_code)]

use std::collections::BTreeMap;

// An opaque payload is bytes the contract forbids us to reinterpret, and String
// would refuse to hold one that is not UTF-8 rather than carry it back out.
pub type Raw = Vec<u8>;

const HEX: &[u8; 16] = b"0123456789abcdef";

fn esc_byte(out: &mut Vec<u8>, c: u8) {
    match c {
        b'"' => out.extend_from_slice(b"\\\""),
        b'\\' => out.extend_from_slice(b"\\\\"),
        0x08 => out.extend_from_slice(b"\\b"),
        0x0c => out.extend_from_slice(b"\\f"),
        b'\n' => out.extend_from_slice(b"\\n"),
        b'\r' => out.extend_from_slice(b"\\r"),
        b'\t' => out.extend_from_slice(b"\\t"),
        _ if c < 0x20 => {
            out.extend_from_slice(b"\\u00");
            out.push(HEX[(c >> 4) as usize]);
            out.push(HEX[(c & 0x0F) as usize]);
        }
        _ => out.push(c),
    }
}

pub fn num(out: &mut Vec<u8>, n: i64) {
    out.extend_from_slice(n.to_string().as_bytes());
}

pub fn pad(out: &mut Vec<u8>, depth: i32) {
    for _ in 0..depth * 2 {
        out.push(b' ');
    }
}

pub fn strs(out: &mut Vec<u8>, v: &[String], depth: i32) {
    if v.is_empty() {
        out.extend_from_slice(b"[]");
        return;
    }
    out.extend_from_slice(b"[\n");
    for (i, s) in v.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, s);
        if i + 1 < v.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b']');
}

fn ws(c: u8) -> bool {
    c == b' ' || c == b'\t' || c == b'\n' || c == b'\r'
}

pub fn raw(out: &mut Vec<u8>, b: &[u8], depth: i32) {
    let mut depth = depth;
    let mut i = 0;
    while i < b.len() {
        let c = b[i];
        if ws(c) {
            i += 1;
        } else if c == b'"' {
            let mut j = i + 1;
            while j < b.len() {
                if b[j] == b'\\' {
                    j += 2;
                    continue;
                }
                if b[j] == b'"' {
                    j += 1;
                    break;
                }
                j += 1;
            }
            out.extend_from_slice(&b[i..j]);
            i = j;
        } else if c == b'{' || c == b'[' {
            out.push(c);
            i += 1;
            let mut j = i;
            while j < b.len() && ws(b[j]) {
                j += 1;
            }
            if j < b.len() && (b[j] == b'}' || b[j] == b']') {
                out.push(b[j]);
                i = j + 1;
            } else {
                depth += 1;
                out.push(b'\n');
                pad(out, depth);
            }
        } else if c == b'}' || c == b']' {
            depth -= 1;
            out.push(b'\n');
            pad(out, depth);
            out.push(c);
            i += 1;
        } else if c == b',' {
            out.extend_from_slice(b",\n");
            pad(out, depth);
            i += 1;
        } else if c == b':' {
            out.extend_from_slice(b": ");
            i += 1;
        } else {
            out.push(c);
            i += 1;
        }
    }
}

// A BTreeMap<String, _> walks its keys in String's Ord, which compares the
// UTF-8 bytes — the order the definition declares. Nothing sorts here.
pub fn rawmap(out: &mut Vec<u8>, m: &BTreeMap<String, Raw>, depth: i32) {
    if m.is_empty() {
        out.extend_from_slice(b"{}");
        return;
    }
    out.extend_from_slice(b"{\n");
    for (i, (k, v)) in m.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, k);
        out.extend_from_slice(b": ");
        raw(out, v, depth + 1);
        if i + 1 < m.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b'}');
}

pub fn esc(out: &mut Vec<u8>, s: &str) {
    out.push(b'"');
    for c in s.as_bytes() {
        esc_byte(out, *c);
    }
    out.push(b'"');
}

pub fn strmap(out: &mut Vec<u8>, m: &BTreeMap<String, String>, depth: i32) {
    if m.is_empty() {
        out.extend_from_slice(b"{}");
        return;
    }
    out.extend_from_slice(b"{\n");
    for (i, (k, v)) in m.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, k);
        out.extend_from_slice(b": ");
        esc(out, v);
        if i + 1 < m.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_list<T>(out: &mut Vec<u8>, v: &[T], depth: i32, enc: fn(&mut Vec<u8>, &T, i32)) {
    if v.is_empty() {
        out.extend_from_slice(b"[]");
        return;
    }
    out.extend_from_slice(b"[\n");
    for (i, x) in v.iter().enumerate() {
        pad(out, depth + 1);
        enc(out, x, depth + 1);
        if i + 1 < v.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b']');
}

pub const PAGEOUTCOME_NAMES: [&str; 7] = ["page", "gap", "unavailable", "invalid_request", "record_too_large", "corrupt", "unsupported"];
pub const PAGEOUTCOME_UNKNOWN: &str = "refuse";

#[derive(Default)]
pub struct Attestation {
    pub by: String,
    pub verified: bool,
    pub hop: i64,
    pub program: String,
    pub host: String,
    pub user: String,
    pub exe: String,
    pub uid: i64,
    pub gid: i64,
    pub pid: i64,
    pub key: String,
    pub mac: String,
}

#[derive(Default)]
pub struct Record {
    pub schema: i64,
    pub time: String,
    pub level: i64,
    pub msg: String,
    pub identity: Vec<Attestation>,
    pub job: String,
    pub attrs: BTreeMap<String, String>,
}

#[derive(Default)]
pub struct Page {
    pub outcome: String,
    pub records: Vec<Record>,
    pub next: String,
    pub at_end: bool,
}

#[derive(Default)]
pub struct OASinkWriteArguments {
    pub record: Record,
}

#[derive(Default)]
pub struct OAHistoryReaderReadArguments {
    pub cursor: String,
    pub max_records: i64,
    pub max_bytes: i64,
}

#[derive(Default)]
pub struct OAHistoryObserverObserveArguments {
    pub cursor: String,
    pub max_records: i64,
    pub max_bytes: i64,
    pub wait_ms: i64,
}

#[derive(Default)]
pub struct OAServiceFrame {
    pub version: i32,
    pub service: String,
    pub method: String,
    pub arguments: Raw,
}

#[derive(Default)]
pub struct OAServiceReply {
    pub version: i32,
    pub service: String,
    pub method: String,
    pub ok: bool,
    pub payload: Raw,
}

#[derive(Default)]
pub struct OAServiceError {
    pub code: String,
    pub message: String,
}

#[derive(Default)]
pub struct OAHistoryReaderReadResult {
    pub value: Page,
}

#[derive(Default)]
pub struct OAHistoryObserverObserveResult {
    pub value: Page,
}

pub fn enc_attestation(out: &mut Vec<u8>, v: &Attestation, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "by");
    out.extend_from_slice(b": ");
    esc(out, &v.by);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "verified");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.verified { b"true" } else { b"false" });
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "hop");
    out.extend_from_slice(b": ");
    num(out, v.hop);
    if !v.program.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "program");
        out.extend_from_slice(b": ");
        esc(out, &v.program);
    }
    if !v.host.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "host");
        out.extend_from_slice(b": ");
        esc(out, &v.host);
    }
    if !v.user.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "user");
        out.extend_from_slice(b": ");
        esc(out, &v.user);
    }
    if !v.exe.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "exe");
        out.extend_from_slice(b": ");
        esc(out, &v.exe);
    }
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "uid");
    out.extend_from_slice(b": ");
    num(out, v.uid);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "gid");
    out.extend_from_slice(b": ");
    num(out, v.gid);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "pid");
    out.extend_from_slice(b": ");
    num(out, v.pid);
    if !v.key.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "key");
        out.extend_from_slice(b": ");
        esc(out, &v.key);
    }
    if !v.mac.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "mac");
        out.extend_from_slice(b": ");
        esc(out, &v.mac);
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_record(out: &mut Vec<u8>, v: &Record, depth: i32) {
    if v.schema != 1 { std::panic::panic_any(Refusal{word:"bad_schema",offset:0}); }
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "schema");
    out.extend_from_slice(b": ");
    num(out, v.schema);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "time");
    out.extend_from_slice(b": ");
    esc(out, &write_timestamp(&v.time));
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "level");
    out.extend_from_slice(b": ");
    num(out, v.level);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "msg");
    out.extend_from_slice(b": ");
    esc(out, &v.msg);
    if !v.identity.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "identity");
        out.extend_from_slice(b": ");
        enc_list(out, &v.identity, depth + 1, enc_attestation);
    }
    if !v.job.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "job");
        out.extend_from_slice(b": ");
        esc(out, &v.job);
    }
    if !v.attrs.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "attrs");
        out.extend_from_slice(b": ");
        strmap(out, &v.attrs, depth + 1);
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_page(out: &mut Vec<u8>, v: &Page, depth: i32) {
    if v.outcome != "page" && v.outcome != "gap" && v.outcome != "unavailable" && v.outcome != "invalid_request" && v.outcome != "record_too_large" && v.outcome != "corrupt" && v.outcome != "unsupported" { std::panic::panic_any(Refusal{word:"bad_enum",offset:0}); }
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "outcome");
    out.extend_from_slice(b": ");
    esc(out, &v.outcome);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "records");
    out.extend_from_slice(b": ");
    enc_list(out, &v.records, depth + 1, enc_record);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "next");
    out.extend_from_slice(b": ");
    esc(out, &v.next);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "at_end");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.at_end { b"true" } else { b"false" });
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oasinkwritearguments(out: &mut Vec<u8>, v: &OASinkWriteArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "record");
    out.extend_from_slice(b": ");
    enc_record(out, &v.record, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oahistoryreaderreadarguments(out: &mut Vec<u8>, v: &OAHistoryReaderReadArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "cursor");
    out.extend_from_slice(b": ");
    esc(out, &v.cursor);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "max_records");
    out.extend_from_slice(b": ");
    num(out, v.max_records);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "max_bytes");
    out.extend_from_slice(b": ");
    num(out, v.max_bytes);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oahistoryobserverobservearguments(out: &mut Vec<u8>, v: &OAHistoryObserverObserveArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "cursor");
    out.extend_from_slice(b": ");
    esc(out, &v.cursor);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "max_records");
    out.extend_from_slice(b": ");
    num(out, v.max_records);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "max_bytes");
    out.extend_from_slice(b": ");
    num(out, v.max_bytes);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "wait_ms");
    out.extend_from_slice(b": ");
    num(out, v.wait_ms);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaserviceframe(out: &mut Vec<u8>, v: &OAServiceFrame, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "version");
    out.extend_from_slice(b": ");
    num(out, v.version as i64);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "service");
    out.extend_from_slice(b": ");
    esc(out, &v.service);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "method");
    out.extend_from_slice(b": ");
    esc(out, &v.method);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "arguments");
    out.extend_from_slice(b": ");
    out.extend_from_slice(&v.arguments);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaservicereply(out: &mut Vec<u8>, v: &OAServiceReply, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "version");
    out.extend_from_slice(b": ");
    num(out, v.version as i64);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "service");
    out.extend_from_slice(b": ");
    esc(out, &v.service);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "method");
    out.extend_from_slice(b": ");
    esc(out, &v.method);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "ok");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.ok { b"true" } else { b"false" });
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "payload");
    out.extend_from_slice(b": ");
    out.extend_from_slice(&v.payload);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaserviceerror(out: &mut Vec<u8>, v: &OAServiceError, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "code");
    out.extend_from_slice(b": ");
    esc(out, &v.code);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "message");
    out.extend_from_slice(b": ");
    esc(out, &v.message);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oahistoryreaderreadresult(out: &mut Vec<u8>, v: &OAHistoryReaderReadResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_page(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oahistoryobserverobserveresult(out: &mut Vec<u8>, v: &OAHistoryObserverObserveResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_page(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn encode(v: &Record) -> Vec<u8> {
    let mut out = Vec::new();
    enc_record(&mut out, v, 0);
    out.push(b'\n');
    out
}

const DEPTH_LIMIT: i32 = 64;

#[derive(Debug)]
pub struct Refusal {
    pub word: &'static str,
    pub offset: usize,
}

impl std::fmt::Display for Refusal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "refused: {} at byte {}", self.word, self.offset)
    }
}

impl std::error::Error for Refusal {}

fn append_rune(out: &mut Vec<u8>, cp: u32) {
    if cp < 0x80 {
        out.push(cp as u8);
    } else if cp < 0x800 {
        out.push(0xC0 | (cp >> 6) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else if cp < 0x10000 {
        out.push(0xE0 | (cp >> 12) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else {
        out.push(0xF0 | (cp >> 18) as u8);
        out.push(0x80 | ((cp >> 12) & 0x3F) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    }
}

struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
    depth: i32,
}

impl<'a> Reader<'a> {
    fn refuse<T>(&self, word: &'static str) -> Result<T, Refusal> {
        Err(Refusal { word, offset: self.pos })
    }

    fn at(&self) -> u8 {
        if self.pos < self.buf.len() { self.buf[self.pos] } else { 0 }
    }

    fn skip_ws(&mut self) {
        while self.pos < self.buf.len() && ws(self.buf[self.pos]) {
            self.pos += 1;
        }
    }

    fn enter(&mut self) -> Result<(), Refusal> {
        self.depth += 1;
        if self.depth > DEPTH_LIMIT {
            return self.refuse("depth_exceeded");
        }
        Ok(())
    }

    fn string(&mut self) -> Result<String, Refusal> {
        if self.at() != b'"' {
            return self.refuse("wrong_type");
        }
        self.pos += 1;
        let mut out: Vec<u8> = Vec::new();
        loop {
            if self.pos >= self.buf.len() {
                return self.refuse("malformed");
            }
            let c = self.buf[self.pos];
            if c == b'"' {
                self.pos += 1;
                return match String::from_utf8(out) {
                    Ok(s) => Ok(s),
                    Err(_) => self.refuse("bad_string"),
                };
            }
            if c < 0x20 {
                return self.refuse("bad_string");
            }
            if c == b'\\' {
                self.escape(&mut out)?;
            } else {
                out.push(c);
                self.pos += 1;
            }
        }
    }

    fn escape(&mut self, out: &mut Vec<u8>) -> Result<(), Refusal> {
        self.pos += 1;
        if self.pos >= self.buf.len() {
            return self.refuse("malformed");
        }
        let c = self.buf[self.pos];
        self.pos += 1;
        match c {
            b'"' | b'\\' | b'/' => out.push(c),
            b'b' => out.push(0x08),
            b'f' => out.push(0x0c),
            b'n' => out.push(b'\n'),
            b'r' => out.push(b'\r'),
            b't' => out.push(b'\t'),
            b'u' => {
                let mut u = self.hex4()?;
                if (0xDC00..=0xDFFF).contains(&u) {
                    return self.refuse("bad_string");
                }
                if (0xD800..=0xDBFF).contains(&u) {
                    if self.pos + 1 >= self.buf.len()
                        || self.buf[self.pos] != b'\\'
                        || self.buf[self.pos + 1] != b'u'
                    {
                        return self.refuse("bad_string");
                    }
                    self.pos += 2;
                    let low = self.hex4()?;
                    if !(0xDC00..=0xDFFF).contains(&low) {
                        return self.refuse("bad_string");
                    }
                    u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
                }
                append_rune(out, u);
            }
            _ => return self.refuse("bad_string"),
        }
        Ok(())
    }

    fn hex4(&mut self) -> Result<u32, Refusal> {
        if self.pos + 4 > self.buf.len() {
            return self.refuse("bad_string");
        }
        let mut u: u32 = 0;
        for i in 0..4 {
            let c = self.buf[self.pos + i];
            let d = match c {
                b'0'..=b'9' => c - b'0',
                b'a'..=b'f' => c - b'a' + 10,
                b'A'..=b'F' => c - b'A' + 10,
                _ => return self.refuse("bad_string"),
            };
            u = u << 4 | d as u32;
        }
        self.pos += 4;
        Ok(u)
    }

    fn integer(&mut self, low: i64, high: i64) -> Result<i64, Refusal> {
        let c = self.at();
        if c != b'-' && !c.is_ascii_digit() {
            return self.refuse("wrong_type");
        }
        let negative = c == b'-';
        if negative {
            self.pos += 1;
        }
        if !self.at().is_ascii_digit() {
            return self.refuse("malformed");
        }
        let mut u: u64 = 0;
        if self.at() == b'0' {
            self.pos += 1;
        } else {
            while self.at().is_ascii_digit() {
                if u > 922337203685477580 {
                    return self.refuse("number_spelling");
                }
                u = u * 10 + (self.at() - b'0') as u64;
                self.pos += 1;
            }
        }
        let after = self.at();
        if after == b'.' || after == b'e' || after == b'E' || after.is_ascii_digit() {
            return self.refuse("number_spelling");
        }
        if negative && u == 0 {
            return self.refuse("number_spelling");
        }
        let n = if negative {
            if u > 1u64 << 63 {
                return self.refuse("number_spelling");
            }
            if u == 1u64 << 63 { i64::MIN } else { -(u as i64) }
        } else {
            if u > i64::MAX as u64 {
                return self.refuse("number_spelling");
            }
            u as i64
        };
        if n < low || n > high {
            return self.refuse("number_spelling");
        }
        Ok(n)
    }

    fn boolean(&mut self) -> Result<bool, Refusal> {
        match self.at() {
            b't' => {
                self.literal(b"true")?;
                Ok(true)
            }
            b'f' => {
                self.literal(b"false")?;
                Ok(false)
            }
            _ => self.refuse("wrong_type"),
        }
    }

    fn literal(&mut self, word: &[u8]) -> Result<(), Refusal> {
        if self.pos + word.len() > self.buf.len() || &self.buf[self.pos..self.pos + word.len()] != word {
            return self.refuse("malformed");
        }
        self.pos += word.len();
        Ok(())
    }

    fn str_list(&mut self) -> Result<Vec<String>, Refusal> {
        if self.at() != b'[' {
            return self.refuse("wrong_type");
        }
        self.enter()?;
        self.pos += 1;
        let mut out = Vec::new();
        self.skip_ws();
        if self.at() != b']' {
            loop {
                self.skip_ws();
                out.push(self.string()?);
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != b']' {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(out)
    }

    fn raw_map(&mut self) -> Result<BTreeMap<String, Raw>, Refusal> {
        if self.at() != b'{' {
            return self.refuse("wrong_type");
        }
        self.enter()?;
        self.pos += 1;
        let mut out = BTreeMap::new();
        self.skip_ws();
        if self.at() != b'}' {
            loop {
                self.skip_ws();
                if self.at() != b'"' {
                    return self.refuse("malformed");
                }
                let k = self.string()?;
                self.skip_ws();
                if self.at() != b':' {
                    return self.refuse("malformed");
                }
                self.pos += 1;
                self.skip_ws();
                let v = self.raw_value()?;
                out.insert(k, v);
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != b'}' {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(out)
    }

    fn raw_value(&mut self) -> Result<Raw, Refusal> {
        let start = self.pos;
        self.skip_value()?;
        Ok(self.buf[start..self.pos].to_vec())
    }

    fn skip_value(&mut self) -> Result<(), Refusal> {
        let c = self.at();
        match c {
            b'"' => self.skip_string(),
            b'{' | b'[' => self.skip_container(),
            b't' => self.literal(b"true"),
            b'f' => self.literal(b"false"),
            b'n' => self.literal(b"null"),
            b'-' => self.skip_number(),
            _ if c.is_ascii_digit() => self.skip_number(),
            _ => self.refuse("malformed"),
        }
    }

    // An opaque value is validated and carried, never interpreted. Its syntax is
    // the record's own — the same string reader, so an escape, a control byte or
    // a lone surrogate is judged identically at any depth — and what it is free
    // to spell, it keeps: the bytes between these two offsets are what a writer
    // re-emits. A number is walked, never converted, so a value no host type
    // holds survives the reader that carried it.
    fn skip_string(&mut self) -> Result<(), Refusal> {
        self.string()?;
        Ok(())
    }

    fn some_digits(&mut self) -> Result<(), Refusal> {
        let mut n = 0;
        while self.at().is_ascii_digit() {
            self.pos += 1;
            n += 1;
        }
        if n == 0 {
            return self.refuse("number_spelling");
        }
        Ok(())
    }

    fn skip_number(&mut self) -> Result<(), Refusal> {
        if self.at() == b'-' {
            self.pos += 1;
        }
        match self.at() {
            b'0' => self.pos += 1,
            c if c.is_ascii_digit() => {
                while self.at().is_ascii_digit() {
                    self.pos += 1;
                }
            }
            _ => return self.refuse("number_spelling"),
        }
        if self.at() == b'.' {
            self.pos += 1;
            self.some_digits()?;
        }
        if self.at() == b'e' || self.at() == b'E' {
            self.pos += 1;
            if self.at() == b'+' || self.at() == b'-' {
                self.pos += 1;
            }
            self.some_digits()?;
        }
        Ok(())
    }

    fn skip_container(&mut self) -> Result<(), Refusal> {
        let opener = self.at();
        let shut = if opener == b'{' { b'}' } else { b']' };
        self.enter()?;
        self.pos += 1;
        self.skip_ws();
        if self.at() != shut {
            loop {
                self.skip_ws();
                if opener == b'{' {
                    if self.at() != b'"' {
                        return self.refuse("malformed");
                    }
                    self.string()?;
                    self.skip_ws();
                    if self.at() != b':' {
                        return self.refuse("malformed");
                    }
                    self.pos += 1;
                    self.skip_ws();
                }
                self.skip_value()?;
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != shut {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(())
    }
}

fn str_map(r: &mut Reader) -> Result<BTreeMap<String, String>, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut out = BTreeMap::new();
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let k = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            let v = r.string()?;
            out.insert(k, v);
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(out)
}

fn decode_list<T>(
    r: &mut Reader,
    elem: fn(&mut Reader) -> Result<T, Refusal>,
) -> Result<Vec<T>, Refusal> {
    if r.at() != b'[' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut out = Vec::new();
    r.skip_ws();
    if r.at() != b']' {
        loop {
            r.skip_ws();
            out.push(elem(r)?);
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b']' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(out)
}

fn digits(s: &[u8], i: usize, n: usize) -> bool {
    s.len() >= i + n && s[i..i + n].iter().all(|c| c.is_ascii_digit())
}

fn date_part(s: &[u8]) -> bool {
    s.len() >= 19
        && digits(s, 0, 4) && s[4] == b'-' && digits(s, 5, 2) && s[7] == b'-' && digits(s, 8, 2)
        && digits(s, 11, 2) && s[13] == b':' && digits(s, 14, 2) && s[16] == b':' && digits(s, 17, 2)
}

/// [DEF-G1] rfc3339-wide: what a reader accepts. Any fraction of one to nine
/// digits or none, either case of the separators, and a numeric offset.
fn lexical_timestamp(text: &str) -> bool {
    let s = text.as_bytes();
    if !date_part(s) || (s[10] != b'T' && s[10] != b't') {
        return false;
    }
    let mut i = 19;
    if i < s.len() && s[i] == b'.' {
        i += 1;
        let start = i;
        while i < s.len() && s[i].is_ascii_digit() {
            i += 1;
        }
        if i - start < 1 || i - start > 9 {
            return false;
        }
    }
    if i >= s.len() {
        return false;
    }
    if s[i] == b'Z' || s[i] == b'z' {
        return i + 1 == s.len();
    }
    if s[i] != b'+' && s[i] != b'-' {
        return false;
    }
    s.len() == i + 6 && digits(s, i + 1, 2) && s[i + 3] == b':' && digits(s, i + 4, 2)
}

/// [DEF-G2] rfc3339-micros: what a writer emits. Exactly six fractional digits,
/// upper-case separators, UTC.
pub fn micros_timestamp(text: &str) -> bool {
    text.len() == 27 && normalized_timestamp(text) == text
}

fn read_timestamp(r: &mut Reader) -> Result<String, Refusal> {
    let at = r.pos;
    let s = r.string()?;
    if !wide_timestamp(&s) {
        r.pos = at;
        return r.refuse("bad_timestamp");
    }
    Ok(s)
}

fn timestamp_number(s: &[u8], at: usize, n: usize) -> i32 {
    s[at..at+n].iter().fold(0, |v,c| v*10+i32::from(c-b'0'))
}
fn timestamp_days(y: i32, m: i32) -> i32 {
    if m==2 {return if y%4==0 && (y%100!=0 || y%400==0) {29} else {28};}
    if m==4 || m==6 || m==9 || m==11 {30} else {31}
}
fn normalized_timestamp(text: &str) -> String {
    if !lexical_timestamp(text) {return String::new();}
    let s=text.as_bytes();
    let (mut y,mut m,mut d)=(timestamp_number(s,0,4),timestamp_number(s,5,2),timestamp_number(s,8,2));
    let (h,minute,sec)=(timestamp_number(s,11,2),timestamp_number(s,14,2),timestamp_number(s,17,2));
    if m<1 || m>12 || d<1 || d>timestamp_days(y,m) || h>23 || minute>59 || sec>59 {return String::new();}
    let mut i=19; let mut fraction=&s[0..0];
    if s[i]==b'.' {i+=1; let start=i; while s[i].is_ascii_digit() {i+=1;} fraction=&s[start..i];}
    let mut total=h*60+minute;
    if s[i]==b'+' || s[i]==b'-' {
        let (oh,om)=(timestamp_number(s,i+1,2),timestamp_number(s,i+4,2));
        if oh>23 || om>59 {return String::new();}
        total += (if s[i]==b'+' {-1} else {1})*(oh*60+om);
    }
    if total<0 {total+=1440; d-=1;} else if total>=1440 {total-=1440; d+=1;}
    if d==0 {m-=1; if m==0 {y-=1; m=12;} d=timestamp_days(y,m);}
    if d>timestamp_days(y,m) {d=1; m+=1; if m==13 {y+=1; m=1;}}
    if !(0..=9999).contains(&y) {return String::new();}
    let mut out=*b"0000-00-00T00:00:00.000000Z";
    let mut put=|at: usize,width: usize,mut value: i32| {for k in (0..width).rev() {out[at+k]=b'0'+(value%10) as u8; value/=10;}};
    put(0,4,y); put(5,2,m); put(8,2,d); put(11,2,total/60); put(14,2,total%60); put(17,2,sec);
    for k in 0..fraction.len().min(6) {out[20+k]=fraction[k];}
    String::from_utf8(out.to_vec()).unwrap()
}
pub fn wide_timestamp(text: &str) -> bool {!normalized_timestamp(text).is_empty()}
fn write_timestamp(text: &str) -> String {
    let result=normalized_timestamp(text);
    assert!(!result.is_empty(), "bad_timestamp");
    result
}

fn decode_attestation(r: &mut Reader) -> Result<Attestation, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Attestation::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "by" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.by = r.string()?;
                }
                "verified" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.verified = r.boolean()?;
                }
                "hop" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.hop = r.integer(i64::MIN, i64::MAX)?;
                }
                "program" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.program = r.string()?;
                }
                "host" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.host = r.string()?;
                }
                "user" => {
                    if seen & 32 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 32;
                    v.user = r.string()?;
                }
                "exe" => {
                    if seen & 64 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 64;
                    v.exe = r.string()?;
                }
                "uid" => {
                    if seen & 128 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 128;
                    v.uid = r.integer(i64::MIN, i64::MAX)?;
                }
                "gid" => {
                    if seen & 256 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 256;
                    v.gid = r.integer(i64::MIN, i64::MAX)?;
                }
                "pid" => {
                    if seen & 512 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 512;
                    v.pid = r.integer(i64::MIN, i64::MAX)?;
                }
                "key" => {
                    if seen & 1024 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1024;
                    v.key = r.string()?;
                }
                "mac" => {
                    if seen & 2048 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2048;
                    v.mac = r.string()?;
                }
                _ => {
                    r.skip_value()?;
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 903 != 903 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_record(r: &mut Reader) -> Result<Record, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Record::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "schema" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.schema = r.integer(i64::MIN, i64::MAX)?;
                }
                "time" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.time = read_timestamp(r)?;
                }
                "level" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.level = r.integer(i64::MIN, i64::MAX)?;
                }
                "msg" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.msg = r.string()?;
                }
                "identity" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.identity = decode_list(r, decode_attestation)?;
                }
                "job" => {
                    if seen & 32 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 32;
                    v.job = r.string()?;
                }
                "attrs" => {
                    if seen & 64 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 64;
                    v.attrs = str_map(r)?;
                }
                _ => {
                    r.skip_value()?;
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    if v.schema != 1 { return r.refuse("bad_schema"); }
    Ok(v)
}

fn decode_page(r: &mut Reader) -> Result<Page, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Page::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "outcome" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.outcome = r.string()?;
                }
                "records" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.records = decode_list(r, decode_record)?;
                }
                "next" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.next = r.string()?;
                }
                "at_end" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.at_end = r.boolean()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    if v.outcome != "page" && v.outcome != "gap" && v.outcome != "unavailable" && v.outcome != "invalid_request" && v.outcome != "record_too_large" && v.outcome != "corrupt" && v.outcome != "unsupported" { return r.refuse("bad_enum"); }
    Ok(v)
}

fn decode_oasinkwritearguments(r: &mut Reader) -> Result<OASinkWriteArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OASinkWriteArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "record" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.record = decode_record(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oahistoryreaderreadarguments(r: &mut Reader) -> Result<OAHistoryReaderReadArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAHistoryReaderReadArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "cursor" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.cursor = r.string()?;
                }
                "max_records" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.max_records = r.integer(i64::MIN, i64::MAX)?;
                }
                "max_bytes" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.max_bytes = r.integer(i64::MIN, i64::MAX)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 7 != 7 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oahistoryobserverobservearguments(r: &mut Reader) -> Result<OAHistoryObserverObserveArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAHistoryObserverObserveArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "cursor" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.cursor = r.string()?;
                }
                "max_records" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.max_records = r.integer(i64::MIN, i64::MAX)?;
                }
                "max_bytes" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.max_bytes = r.integer(i64::MIN, i64::MAX)?;
                }
                "wait_ms" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.wait_ms = r.integer(i64::MIN, i64::MAX)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaserviceframe(r: &mut Reader) -> Result<OAServiceFrame, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAServiceFrame::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "version" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.version = r.integer(-2147483648, 2147483647)? as i32;
                }
                "service" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.service = r.string()?;
                }
                "method" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.method = r.string()?;
                }
                "arguments" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.arguments = r.raw_value()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaservicereply(r: &mut Reader) -> Result<OAServiceReply, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAServiceReply::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "version" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.version = r.integer(-2147483648, 2147483647)? as i32;
                }
                "service" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.service = r.string()?;
                }
                "method" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.method = r.string()?;
                }
                "ok" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.ok = r.boolean()?;
                }
                "payload" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.payload = r.raw_value()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 31 != 31 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaserviceerror(r: &mut Reader) -> Result<OAServiceError, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAServiceError::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "code" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.code = r.string()?;
                }
                "message" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.message = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oahistoryreaderreadresult(r: &mut Reader) -> Result<OAHistoryReaderReadResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAHistoryReaderReadResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_page(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oahistoryobserverobserveresult(r: &mut Reader) -> Result<OAHistoryObserverObserveResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAHistoryObserverObserveResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_page(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

pub fn decode(data: &[u8]) -> Result<Record, Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth: 0 };
    r.skip_ws();
    let v = decode_record(&mut r)?;
    r.skip_ws();
    if r.pos < r.buf.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}

// REFUSALS is in the order two of them are chosen between.
pub const REFUSALS: [&str; 12] = ["malformed", "bad_string", "number_spelling", "wrong_type", "bad_timestamp", "depth_exceeded", "duplicate_field", "unknown_field", "missing_field", "bad_schema", "bad_enum", "trailing_bytes"];

pub fn refusal_rank(word: &str) -> i32 {
    match REFUSALS.iter().position(|w| *w == word) {
        Some(i) => i as i32,
        None => -1,
    }
}

#[allow(unused_variables)]
fn service_check_attestation(v: &Attestation) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_record(v: &Record) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if v.schema != 1 { return r.refuse("bad_schema"); }
    for value in &v.identity { service_check_attestation(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_page(v: &Page) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if v.outcome != "page" && v.outcome != "gap" && v.outcome != "unavailable" && v.outcome != "invalid_request" && v.outcome != "record_too_large" && v.outcome != "corrupt" && v.outcome != "unsupported" { return r.refuse("bad_enum"); }
    for value in &v.records { service_check_record(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oasinkwritearguments(v: &OASinkWriteArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_record(&v.record)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oahistoryreaderreadarguments(v: &OAHistoryReaderReadArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oahistoryobserverobservearguments(v: &OAHistoryObserverObserveArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaserviceframe(v: &OAServiceFrame) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaservicereply(v: &OAServiceReply) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaserviceerror(v: &OAServiceError) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oahistoryreaderreadresult(v: &OAHistoryReaderReadResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_page(&v.value)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oahistoryobserverobserveresult(v: &OAHistoryObserverObserveResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_page(&v.value)?;
    Ok(())
}

/// Common generated framing boundary; implementation owns waiting and identity.
pub use abstraction_frame::FrameTransport;

#[derive(Debug)]
pub struct ServiceError { pub code: String, pub message: String }
#[derive(Debug)]
pub enum CallError<E> {
    /// Transport failure does not establish whether the receiver accepted work.
    Transport(E),
    Refusal(Refusal),
    Dispatch(&'static str),
    Service(ServiceError),
}
fn service_decode<T>(data: &[u8], decode: fn(&mut Reader) -> Result<T, Refusal>) -> Result<T, Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth: 0 };
    r.skip_ws();
    let value = decode(&mut r)?;
    r.skip_ws();
    if r.pos != data.len() { return r.refuse("trailing_bytes"); }
    Ok(value)
}
fn service_encode<T>(value: &T, check: fn(&T) -> Result<(), Refusal>, encode: fn(&mut Vec<u8>, &T, i32), decode: fn(&mut Reader) -> Result<T, Refusal>) -> Result<Vec<u8>, Refusal> {
    check(value)?;
    let mut data = Vec::new();
    encode(&mut data, value, 0);
    service_decode(&data, decode)?;
    Ok(data)
}

#[allow(non_snake_case)]
pub trait Sink {
    type Error;
    fn Write(&self, arg0: Record) -> Result<(), Self::Error>;
}

pub struct SinkClient<T> { transport: T }
impl<T> SinkClient<T> {
    pub fn new(transport: T) -> Self { Self { transport } }
    pub fn transport(&self) -> &T { &self.transport }
}
#[allow(non_snake_case)]
impl<T: FrameTransport> Sink for SinkClient<T> {
    type Error = CallError<T::Error>;
    fn Write(&self, arg0: Record) -> Result<(), Self::Error> {
        let args = OASinkWriteArguments { record: arg0, };
        let arguments = service_encode(&args, service_check_oasinkwritearguments, enc_oasinkwritearguments, decode_oasinkwritearguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.logging/sink@1".into(), method: "Write".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        self.transport.write_frame(&frame).map_err(CallError::Transport)
    }
}

#[allow(non_snake_case)]
pub trait HistoryReader {
    type Error;
    fn Read(&self, arg0: String, arg1: i64, arg2: i64) -> Result<Page, Self::Error>;
}

pub struct HistoryReaderClient<T> { transport: T }
impl<T> HistoryReaderClient<T> {
    pub fn new(transport: T) -> Self { Self { transport } }
    pub fn transport(&self) -> &T { &self.transport }
}
#[allow(non_snake_case)]
impl<T: FrameTransport> HistoryReader for HistoryReaderClient<T> {
    type Error = CallError<T::Error>;
    fn Read(&self, arg0: String, arg1: i64, arg2: i64) -> Result<Page, Self::Error> {
        let args = OAHistoryReaderReadArguments { cursor: arg0, max_records: arg1, max_bytes: arg2, };
        let arguments = service_encode(&args, service_check_oahistoryreaderreadarguments, enc_oahistoryreaderreadarguments, decode_oahistoryreaderreadarguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.logging/reader@1".into(), method: "Read".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.logging/reader@1" || reply.method != "Read" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oahistoryreaderreadresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
}

#[allow(non_snake_case)]
pub trait HistoryObserver {
    type Error;
    fn Observe(&self, arg0: String, arg1: i64, arg2: i64, arg3: i64) -> Result<Page, Self::Error>;
}

pub struct HistoryObserverClient<T> { transport: T }
impl<T> HistoryObserverClient<T> {
    pub fn new(transport: T) -> Self { Self { transport } }
    pub fn transport(&self) -> &T { &self.transport }
}
#[allow(non_snake_case)]
impl<T: FrameTransport> HistoryObserver for HistoryObserverClient<T> {
    type Error = CallError<T::Error>;
    fn Observe(&self, arg0: String, arg1: i64, arg2: i64, arg3: i64) -> Result<Page, Self::Error> {
        let args = OAHistoryObserverObserveArguments { cursor: arg0, max_records: arg1, max_bytes: arg2, wait_ms: arg3, };
        let arguments = service_encode(&args, service_check_oahistoryobserverobservearguments, enc_oahistoryobserverobservearguments, decode_oahistoryobserverobservearguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.logging/observer@1".into(), method: "Observe".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.logging/observer@1" || reply.method != "Observe" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oahistoryobserverobserveresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
}
